# Generated by Django 5.2.16 on 2026-08-15 03:02

import apps.core.fields
import django.contrib.postgres.functions
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_enable_citext"),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('singleton_key', models.SmallIntegerField(db_default=1, default=1, editable=False, unique=True)),
                ('legal_name', models.CharField(max_length=180)),
                ('trade_name', models.CharField(blank=True, max_length=180, null=True)),
                ('ruc', models.CharField(max_length=13)),
                ('domain', apps.core.fields.CITextField(unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_email', apps.core.fields.CIEmailField(max_length=254)),
                ('controller_name', models.CharField(blank=True, max_length=180, null=True)),
                ('controller_email', apps.core.fields.CIEmailField(blank=True, max_length=254, null=True)),
                ('controller_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('dpd_name', models.CharField(blank=True, max_length=180, null=True)),
                ('dpd_email', apps.core.fields.CIEmailField(blank=True, max_length=254, null=True)),
                ('dpd_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('complaint_authority_name', models.CharField(db_default='Superintendencia de Protección de Datos Personales', default='Superintendencia de Protección de Datos Personales', max_length=180)),
                ('complaint_channel_url', models.TextField(blank=True, null=True)),
                ('complaint_instructions', models.TextField(blank=True, null=True)),
                ('request_prefix', models.CharField(max_length=10)),
                ('timezone', models.CharField(db_default='America/Guayaquil', default='America/Guayaquil', max_length=50)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('favicon_url', models.TextField(blank=True, null=True)),
                ('primary_color', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='El color debe utilizar formato hexadecimal #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('secondary_color', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='El color debe utilizar formato hexadecimal #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('accent_color', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='El color debe utilizar formato hexadecimal #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('created_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow())),
            ],
            options={
                'db_table': 'system_settings',
                'constraints': [models.UniqueConstraint(fields=('ruc',), name='uq_system_settings_ruc'), models.CheckConstraint(condition=models.Q(('singleton_key', 1)), name='ck_system_settings_singleton'), models.CheckConstraint(condition=models.Q(('primary_color__isnull', True), ('primary_color__regex', '^#[0-9A-Fa-f]{6}$'), _connector='OR'), name='ck_system_settings_primary_color'), models.CheckConstraint(condition=models.Q(('secondary_color__isnull', True), ('secondary_color__regex', '^#[0-9A-Fa-f]{6}$'), _connector='OR'), name='ck_system_settings_secondary_color'), models.CheckConstraint(condition=models.Q(('accent_color__isnull', True), ('accent_color__regex', '^#[0-9A-Fa-f]{6}$'), _connector='OR'), name='ck_system_settings_accent_color')],
            },
        ),
    ]
