# Generated by Django 5.2.16 on 2026-08-24 14:23

import apps.organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='favicon_image',
            field=models.FileField(blank=True, null=True, upload_to='branding/', validators=[apps.organization.models.validate_branding_image]),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='logo_image',
            field=models.FileField(blank=True, null=True, upload_to='branding/', validators=[apps.organization.models.validate_branding_image]),
        ),
    ]
