# Generated by Django 5.2.16 on 2026-09-08 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_systemsetting_favicon_image_systemsetting_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='active_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='El color debe utilizar formato hexadecimal #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='background_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='El color debe utilizar formato hexadecimal #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='border_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='El color debe utilizar formato hexadecimal #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='error_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='El color debe utilizar formato hexadecimal #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='info_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='El color debe utilizar formato hexadecimal #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='secondary_text_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='El color debe utilizar formato hexadecimal #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='separator_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='El color debe utilizar formato hexadecimal #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='success_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='El color debe utilizar formato hexadecimal #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='warning_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='El color debe utilizar formato hexadecimal #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddConstraint(
            model_name='systemsetting',
            constraint=models.CheckConstraint(condition=models.Q(('background_color__isnull', True), ('background_color__regex', '^#[0-9A-Fa-f]{6}$'), _connector='OR'), name='ck_system_settings_background_color'),
        ),
        migrations.AddConstraint(
            model_name='systemsetting',
            constraint=models.CheckConstraint(condition=models.Q(('active_color__isnull', True), ('active_color__regex', '^#[0-9A-Fa-f]{6}$'), _connector='OR'), name='ck_system_settings_active_color'),
        ),
        migrations.AddConstraint(
            model_name='systemsetting',
            constraint=models.CheckConstraint(condition=models.Q(('separator_color__isnull', True), ('separator_color__regex', '^#[0-9A-Fa-f]{6}$'), _connector='OR'), name='ck_system_settings_separator_color'),
        ),
        migrations.AddConstraint(
            model_name='systemsetting',
            constraint=models.CheckConstraint(condition=models.Q(('border_color__isnull', True), ('border_color__regex', '^#[0-9A-Fa-f]{6}$'), _connector='OR'), name='ck_system_settings_border_color'),
        ),
        migrations.AddConstraint(
            model_name='systemsetting',
            constraint=models.CheckConstraint(condition=models.Q(('secondary_text_color__isnull', True), ('secondary_text_color__regex', '^#[0-9A-Fa-f]{6}$'), _connector='OR'), name='ck_system_settings_secondary_text_color'),
        ),
        migrations.AddConstraint(
            model_name='systemsetting',
            constraint=models.CheckConstraint(condition=models.Q(('success_color__isnull', True), ('success_color__regex', '^#[0-9A-Fa-f]{6}$'), _connector='OR'), name='ck_system_settings_success_color'),
        ),
        migrations.AddConstraint(
            model_name='systemsetting',
            constraint=models.CheckConstraint(condition=models.Q(('info_color__isnull', True), ('info_color__regex', '^#[0-9A-Fa-f]{6}$'), _connector='OR'), name='ck_system_settings_info_color'),
        ),
        migrations.AddConstraint(
            model_name='systemsetting',
            constraint=models.CheckConstraint(condition=models.Q(('warning_color__isnull', True), ('warning_color__regex', '^#[0-9A-Fa-f]{6}$'), _connector='OR'), name='ck_system_settings_warning_color'),
        ),
        migrations.AddConstraint(
            model_name='systemsetting',
            constraint=models.CheckConstraint(condition=models.Q(('error_color__isnull', True), ('error_color__regex', '^#[0-9A-Fa-f]{6}$'), _connector='OR'), name='ck_system_settings_error_color'),
        ),
    ]
