# Generated by Django 5.2.16 on 2026-08-15 02:43

import apps.accounts.fields
import apps.accounts.models
import django.contrib.postgres.functions
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_enable_citext"),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', apps.accounts.fields.CIEmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('is_staff', models.BooleanField(db_default=False, default=False)),
                ('is_superuser', models.BooleanField(db_default=False, default=False)),
                ('failed_login_attempts', models.IntegerField(db_default=0, default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow())),
            ],
            options={
                'db_table': 'users',
                'ordering': ['email'],
                'constraints': [models.CheckConstraint(condition=models.Q(('failed_login_attempts__gte', 0)), name='ck_users_failed_login_attempts_nonnegative')],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('ADMIN', 'Administrador'), ('DPD', 'Delegado de Protección de Datos'), ('RESPONSABLE', 'Responsable del tratamiento'), ('OPERADOR', 'Operador'), ('AUDITOR', 'Auditor')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('created_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('code',), name='uq_roles_code'), models.CheckConstraint(condition=models.Q(('code__in', ['ADMIN', 'DPD', 'RESPONSABLE', 'OPERADOR', 'AUDITOR'])), name='ck_roles_code_valid')],
            },
        ),
        migrations.CreateModel(
            name='MFADevice',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('TOTP', 'TOTP'), ('RECOVERY_CODES', 'Códigos de recuperación')], db_default='TOTP', default='TOTP', max_length=20)),
                ('secret_encrypted', models.BinaryField()),
                ('encryption_key_version', models.SmallIntegerField(db_default=1, default=1)),
                ('is_confirmed', models.BooleanField(db_default=False, default=False)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='mfa_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mfa_devices',
                'indexes': [models.Index(condition=models.Q(('is_active', True), ('revoked_at__isnull', True)), fields=['user'], name='idx_mfa_devices_user_active')],
                'constraints': [models.CheckConstraint(condition=models.Q(('device_type__in', ['TOTP', 'RECOVERY_CODES'])), name='ck_mfa_device_type_valid'), models.CheckConstraint(condition=models.Q(('encryption_key_version__gt', 0)), name='ck_mfa_key_version_positive'), models.CheckConstraint(condition=models.Q(('revoked_at__isnull', True), ('revoked_at__gte', models.F('created_at')), _connector='OR'), name='ck_mfa_revoked_after_created'), models.CheckConstraint(condition=models.Q(('is_confirmed', False), ('confirmed_at__isnull', False), _connector='OR'), name='ck_mfa_confirmed_timestamp')],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(db_default=False, default=False)),
                ('assigned_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, db_column='assigned_by', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_assigned', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='user_assignments', to='accounts.role')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_roles',
                'indexes': [models.Index(fields=['user', '-assigned_at'], name='idx_user_roles_user_history'), models.Index(condition=models.Q(('revoked_at__isnull', True)), fields=['role', 'user'], name='idx_user_roles_role_active')],
                'constraints': [models.CheckConstraint(condition=models.Q(('revoked_at__isnull', True), ('revoked_at__gte', models.F('assigned_at')), _connector='OR'), name='ck_user_roles_revoked_after_assigned'), models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'role'), name='uq_user_active_role'), models.UniqueConstraint(condition=models.Q(('is_primary', True), ('revoked_at__isnull', True)), fields=('user',), name='uq_user_primary_role')],
            },
        ),
    ]
