# Generated by Django 5.2.16 on 2026-08-15 02:45

from django.db import migrations


FORWARD_SQL = """
ALTER TABLE "mfa_devices"
    DROP CONSTRAINT "mfa_devices_user_id_5a090826_fk_users_id";

ALTER TABLE "mfa_devices"
    ADD CONSTRAINT "fk_mfa_devices_user"
    FOREIGN KEY ("user_id")
    REFERENCES "users" ("id")
    ON DELETE CASCADE;


ALTER TABLE "user_roles"
    DROP CONSTRAINT "user_roles_assigned_by_4af38655_fk_users_id";

ALTER TABLE "user_roles"
    ADD CONSTRAINT "fk_user_roles_assigned_by"
    FOREIGN KEY ("assigned_by")
    REFERENCES "users" ("id")
    ON DELETE SET NULL;


ALTER TABLE "user_roles"
    DROP CONSTRAINT "user_roles_role_id_816a4486_fk_roles_id";

ALTER TABLE "user_roles"
    ADD CONSTRAINT "fk_user_roles_role"
    FOREIGN KEY ("role_id")
    REFERENCES "roles" ("id")
    ON DELETE RESTRICT;


ALTER TABLE "user_roles"
    DROP CONSTRAINT "user_roles_user_id_9d9f8dbb_fk_users_id";

ALTER TABLE "user_roles"
    ADD CONSTRAINT "fk_user_roles_user"
    FOREIGN KEY ("user_id")
    REFERENCES "users" ("id")
    ON DELETE CASCADE;
"""


REVERSE_SQL = """
ALTER TABLE "mfa_devices"
    DROP CONSTRAINT "fk_mfa_devices_user";

ALTER TABLE "mfa_devices"
    ADD CONSTRAINT "mfa_devices_user_id_5a090826_fk_users_id"
    FOREIGN KEY ("user_id")
    REFERENCES "users" ("id")
    DEFERRABLE INITIALLY DEFERRED;


ALTER TABLE "user_roles"
    DROP CONSTRAINT "fk_user_roles_assigned_by";

ALTER TABLE "user_roles"
    ADD CONSTRAINT "user_roles_assigned_by_4af38655_fk_users_id"
    FOREIGN KEY ("assigned_by")
    REFERENCES "users" ("id")
    DEFERRABLE INITIALLY DEFERRED;


ALTER TABLE "user_roles"
    DROP CONSTRAINT "fk_user_roles_role";

ALTER TABLE "user_roles"
    ADD CONSTRAINT "user_roles_role_id_816a4486_fk_roles_id"
    FOREIGN KEY ("role_id")
    REFERENCES "roles" ("id")
    DEFERRABLE INITIALLY DEFERRED;


ALTER TABLE "user_roles"
    DROP CONSTRAINT "fk_user_roles_user";

ALTER TABLE "user_roles"
    ADD CONSTRAINT "user_roles_user_id_9d9f8dbb_fk_users_id"
    FOREIGN KEY ("user_id")
    REFERENCES "users" ("id")
    DEFERRABLE INITIALLY DEFERRED;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=FORWARD_SQL,
            reverse_sql=REVERSE_SQL,
        ),
    ]
