# Generated by Django 5.2.16 on 2026-08-15 02:50
from django.db import migrations


ROLES = [
    {
        "code": "ADMIN",
        "name": "Administrador",
        "description": (
            "Administración general de la plataforma, usuarios, "
            "configuración y expedientes."
        ),
    },
    {
        "code": "DPD",
        "name": "Delegado de Protección de Datos",
        "description": (
            "Supervisión de protección de datos, expedientes, "
            "documentación legal y cumplimiento."
        ),
    },
    {
        "code": "RESPONSABLE",
        "name": "Responsable",
        "description": (
            "Gestión y resolución de expedientes dentro del ámbito "
            "operativo autorizado."
        ),
    },
    {
        "code": "OPERADOR",
        "name": "Operador",
        "description": (
            "Gestión operativa de los expedientes que le sean "
            "asignados."
        ),
    },
    {
        "code": "AUDITOR",
        "name": "Auditor",
        "description": (
            "Acceso de consulta para revisión de expedientes, "
            "trazabilidad y auditoría."
        ),
    },
]


def seed_roles(apps, schema_editor):
    Role = apps.get_model(
        "accounts",
        "Role",
    )

    db_alias = schema_editor.connection.alias

    for role_data in ROLES:
        Role.objects.using(db_alias).update_or_create(
            code=role_data["code"],
            defaults={
                "name": role_data["name"],
                "description": role_data["description"],
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_database_fk_actions"),
    ]

    operations = [
        migrations.RunPython(
            seed_roles,
            migrations.RunPython.noop,
        ),
    ]