# Generated by Django 5.2.16 on 2026-08-17 15:45

import apps.core.fields
import django.contrib.postgres.functions
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_database_objects'),
        ('legal_content', '0002_database_fk_actions'),
        ('subjects', '0002_database_fk_actions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(choices=[('IDENTITY_DOCUMENT', 'Documento de identidad'), ('AUTHORITY_DOCUMENT', 'Documento de representación'), ('SUPPORTING_DOCUMENT', 'Documento de respaldo'), ('REQUEST_DOCUMENT', 'Documento de solicitud'), ('RESPONSE_DOCUMENT', 'Documento de respuesta'), ('PORTABILITY_EXPORT', 'Exportación de portabilidad'), ('OTHER', 'Otro')], max_length=40)),
                ('visibility', models.CharField(choices=[('INTERNAL', 'Interno'), ('SUBJECT', 'Visible al titular')], db_default='INTERNAL', default='INTERNAL', max_length=20)),
                ('original_filename_encrypted', models.BinaryField()),
                ('storage_backend', models.CharField(choices=[('LOCAL', 'Local'), ('S3', 'S3'), ('MINIO', 'MinIO')], db_default='LOCAL', default='LOCAL', max_length=20)),
                ('storage_key', models.TextField(unique=True)),
                ('mime_type', models.CharField(max_length=120)),
                ('size_bytes', models.BigIntegerField()),
                ('file_sha256', apps.core.fields.FixedCharField(max_length=64)),
                ('is_encrypted', models.BooleanField(db_default=True, default=True)),
                ('encryption_key_version', models.SmallIntegerField(db_default=1, default=1)),
                ('malware_scan_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CLEAN', 'Limpio'), ('INFECTED', 'Infectado'), ('FAILED', 'Fallido'), ('NOT_APPLICABLE', 'No aplica')], db_default='PENDING', default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('representative', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='subjects.subjectrepresentative')),
                ('request', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.rightsrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'request_attachments',
            },
        ),
        migrations.CreateModel(
            name='TemporaryUpload',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key_hash', apps.core.fields.FixedCharField(max_length=64)),
                ('upload_token_hash', apps.core.fields.FixedCharField(max_length=64, unique=True)),
                ('lookup_key_version', models.SmallIntegerField(db_default=1, default=1)),
                ('attachment_type', models.CharField(choices=[('IDENTITY_DOCUMENT', 'Documento de identidad'), ('AUTHORITY_DOCUMENT', 'Documento de representación'), ('SUPPORTING_DOCUMENT', 'Documento de respaldo'), ('OTHER', 'Otro')], max_length=40)),
                ('original_filename_encrypted', models.BinaryField()),
                ('storage_backend', models.CharField(choices=[('LOCAL', 'Local'), ('S3', 'S3'), ('MINIO', 'MinIO')], db_default='LOCAL', default='LOCAL', max_length=20)),
                ('storage_key', models.TextField(unique=True)),
                ('mime_type', models.CharField(max_length=120)),
                ('size_bytes', models.BigIntegerField()),
                ('file_sha256', apps.core.fields.FixedCharField(max_length=64)),
                ('is_encrypted', models.BooleanField(db_default=True, default=True)),
                ('encryption_key_version', models.SmallIntegerField(db_default=1, default=1)),
                ('malware_scan_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CLEAN', 'Limpio'), ('INFECTED', 'Infectado'), ('FAILED', 'Fallido'), ('NOT_APPLICABLE', 'No aplica')], db_default='PENDING', default='PENDING', max_length=20)),
                ('status', models.CharField(choices=[('UPLOADED', 'Cargado'), ('PROMOTED', 'Promovido'), ('QUARANTINED', 'Cuarentena'), ('EXPIRED', 'Expirado'), ('DELETED', 'Eliminado')], db_default='UPLOADED', default='UPLOADED', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('promoted_attachment', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_sources', to='evidence.requestattachment')),
                ('promoted_request', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_uploads', to='cases.rightsrequest')),
            ],
            options={
                'db_table': 'temporary_uploads',
            },
        ),
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_method', models.CharField(choices=[('STRUCTURAL_DOCUMENT_CHECK', 'Validación estructural de documento'), ('EMAIL_CODE', 'Código por correo'), ('DOCUMENT_REVIEW', 'Revisión documental'), ('IN_PERSON', 'Presencial'), ('MANUAL', 'Manual'), ('OTHER', 'Otro')], max_length=40)),
                ('result', models.CharField(choices=[('PENDING', 'Pendiente'), ('VERIFIED', 'Verificado'), ('REJECTED', 'Rechazado'), ('INCONCLUSIVE', 'No concluyente')], max_length=20)),
                ('validation_metadata', models.JSONField(db_default=models.Value({}, output_field=models.JSONField()), default=dict)),
                ('validation_notes_encrypted', models.BinaryField(blank=True, null=True)),
                ('encryption_key_version', models.SmallIntegerField(db_default=1, default=1)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('request', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='identity_verifications', to='cases.rightsrequest')),
                ('verified_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_verifications',
                'indexes': [models.Index(fields=['request', '-created_at'], name='idx_idv_request'), models.Index(condition=models.Q(('verified_by__isnull', False)), fields=['verified_by', '-created_at'], name='idx_idv_actor')],
                'constraints': [models.CheckConstraint(condition=models.Q(('verification_method__in', ['STRUCTURAL_DOCUMENT_CHECK', 'EMAIL_CODE', 'DOCUMENT_REVIEW', 'IN_PERSON', 'MANUAL', 'OTHER'])), name='ck_idv_method'), models.CheckConstraint(condition=models.Q(('result__in', ['PENDING', 'VERIFIED', 'REJECTED', 'INCONCLUSIVE'])), name='ck_idv_result'), models.CheckConstraint(condition=models.Q(('encryption_key_version__gt', 0)), name='ck_idv_key_version'), models.CheckConstraint(condition=models.Q(('result', 'PENDING'), ('verified_at__isnull', False), _connector='OR'), name='ck_idv_verified_at')],
            },
        ),
        migrations.CreateModel(
            name='NoticeDelivery',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_channel', models.CharField(choices=[('WEB', 'Web'), ('EMAIL', 'Correo electrónico'), ('PHYSICAL', 'Físico'), ('OTHER', 'Otro')], db_default='WEB', default='WEB', max_length=20)),
                ('delivered_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('acknowledged', models.BooleanField(db_default=False, default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('rendered_content_sha256', apps.core.fields.FixedCharField(max_length=64)),
                ('legal_document', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='notice_deliveries', to='legal_content.legaldocument')),
                ('request', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='notice_deliveries', to='cases.rightsrequest')),
            ],
            options={
                'db_table': 'notice_deliveries',
                'indexes': [models.Index(fields=['request', '-delivered_at'], name='idx_notice_request'), models.Index(fields=['legal_document'], name='idx_notice_doc')],
                'constraints': [models.CheckConstraint(condition=models.Q(('delivery_channel__in', ['WEB', 'EMAIL', 'PHYSICAL', 'OTHER'])), name='ck_notice_channel'), models.CheckConstraint(condition=models.Q(('acknowledged', False), ('acknowledged_at__isnull', False), _connector='OR'), name='ck_notice_ack')],
            },
        ),
        migrations.AddIndex(
            model_name='requestattachment',
            index=models.Index(fields=['request', '-uploaded_at'], name='idx_att_request'),
        ),
        migrations.AddIndex(
            model_name='requestattachment',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['request', 'visibility'], name='idx_att_visible'),
        ),
        migrations.AddIndex(
            model_name='requestattachment',
            index=models.Index(condition=models.Q(('representative__isnull', False)), fields=['representative'], name='idx_att_rep'),
        ),
        migrations.AddConstraint(
            model_name='requestattachment',
            constraint=models.CheckConstraint(condition=models.Q(('attachment_type__in', ['IDENTITY_DOCUMENT', 'AUTHORITY_DOCUMENT', 'SUPPORTING_DOCUMENT', 'REQUEST_DOCUMENT', 'RESPONSE_DOCUMENT', 'PORTABILITY_EXPORT', 'OTHER'])), name='ck_att_type'),
        ),
        migrations.AddConstraint(
            model_name='requestattachment',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['INTERNAL', 'SUBJECT'])), name='ck_att_visibility'),
        ),
        migrations.AddConstraint(
            model_name='requestattachment',
            constraint=models.CheckConstraint(condition=models.Q(('storage_backend__in', ['LOCAL', 'S3', 'MINIO'])), name='ck_att_storage'),
        ),
        migrations.AddConstraint(
            model_name='requestattachment',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='ck_att_size'),
        ),
        migrations.AddConstraint(
            model_name='requestattachment',
            constraint=models.CheckConstraint(condition=models.Q(('encryption_key_version__gt', 0)), name='ck_att_key_version'),
        ),
        migrations.AddConstraint(
            model_name='requestattachment',
            constraint=models.CheckConstraint(condition=models.Q(('malware_scan_status__in', ['PENDING', 'CLEAN', 'INFECTED', 'FAILED', 'NOT_APPLICABLE'])), name='ck_att_scan_status'),
        ),
        migrations.AddIndex(
            model_name='temporaryupload',
            index=models.Index(fields=['session_key_hash', 'status'], name='idx_tmp_session'),
        ),
        migrations.AddIndex(
            model_name='temporaryupload',
            index=models.Index(condition=models.Q(('status', 'UPLOADED')), fields=['expires_at'], name='idx_tmp_expiry'),
        ),
        migrations.AddConstraint(
            model_name='temporaryupload',
            constraint=models.CheckConstraint(condition=models.Q(('lookup_key_version__gt', 0)), name='ck_tmp_lookup_version'),
        ),
        migrations.AddConstraint(
            model_name='temporaryupload',
            constraint=models.CheckConstraint(condition=models.Q(('attachment_type__in', ['IDENTITY_DOCUMENT', 'AUTHORITY_DOCUMENT', 'SUPPORTING_DOCUMENT', 'OTHER'])), name='ck_tmp_type'),
        ),
        migrations.AddConstraint(
            model_name='temporaryupload',
            constraint=models.CheckConstraint(condition=models.Q(('storage_backend__in', ['LOCAL', 'S3', 'MINIO'])), name='ck_tmp_storage'),
        ),
        migrations.AddConstraint(
            model_name='temporaryupload',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='ck_tmp_size'),
        ),
        migrations.AddConstraint(
            model_name='temporaryupload',
            constraint=models.CheckConstraint(condition=models.Q(('encryption_key_version__gt', 0)), name='ck_tmp_key_version'),
        ),
        migrations.AddConstraint(
            model_name='temporaryupload',
            constraint=models.CheckConstraint(condition=models.Q(('malware_scan_status__in', ['PENDING', 'CLEAN', 'INFECTED', 'FAILED', 'NOT_APPLICABLE'])), name='ck_tmp_scan_status'),
        ),
        migrations.AddConstraint(
            model_name='temporaryupload',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['UPLOADED', 'PROMOTED', 'QUARANTINED', 'EXPIRED', 'DELETED'])), name='ck_tmp_status'),
        ),
        migrations.AddConstraint(
            model_name='temporaryupload',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='ck_tmp_expiration'),
        ),
        migrations.AddConstraint(
            model_name='temporaryupload',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PROMOTED'), _negated=True), models.Q(('promoted_request__isnull', False), ('promoted_attachment__isnull', False), ('promoted_at__isnull', False)), _connector='OR'), name='ck_tmp_promoted'),
        ),
    ]
