# Generated by Django 5.2.16 on 2026-08-17 15:51

import django.contrib.postgres.functions
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_database_objects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCommunication',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('INBOUND', 'Entrante'), ('OUTBOUND', 'Saliente'), ('SYSTEM', 'Sistema')], max_length=10)),
                ('channel', models.CharField(choices=[('EMAIL', 'Correo electrónico'), ('PORTAL', 'Portal'), ('PHONE', 'Teléfono'), ('PHYSICAL', 'Físico'), ('OTHER', 'Otro')], max_length=20)),
                ('communication_type', models.CharField(choices=[('ACKNOWLEDGEMENT', 'Acuse de recepción'), ('ASSIGNMENT_NOTICE', 'Aviso de asignación'), ('INFORMATION_REQUEST', 'Solicitud de información'), ('CLARIFICATION_REMINDER', 'Recordatorio de aclaración'), ('EXTENSION_NOTICE', 'Aviso de extensión'), ('DEADLINE_ALERT', 'Alerta de vencimiento'), ('RESPONSE', 'Respuesta'), ('REJECTION', 'Rechazo'), ('ARCHIVE_NOTICE', 'Aviso de archivo'), ('CANCELLATION_NOTICE', 'Aviso de cancelación'), ('PORTABILITY_READY', 'Portabilidad disponible'), ('COMPLAINT_INFORMATION', 'Información de reclamación'), ('DELIVERY_FAILURE_ALERT', 'Alerta de fallo de entrega'), ('OTHER', 'Otro')], max_length=40)),
                ('visible_to_subject', models.BooleanField(db_default=False, default=False)),
                ('recipient_encrypted', models.BinaryField(blank=True, null=True)),
                ('subject_encrypted', models.BinaryField(blank=True, null=True)),
                ('body_encrypted', models.BinaryField(blank=True, null=True)),
                ('encryption_key_version', models.SmallIntegerField(db_default=1, default=1)),
                ('idempotency_key', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, unique=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('SENT', 'Enviado'), ('DELIVERED', 'Entregado'), ('FAILED', 'Fallido'), ('RECEIVED', 'Recibido'), ('CANCELLED', 'Cancelado')], db_default='PENDING', default='PENDING', max_length=20)),
                ('attempt_count', models.IntegerField(db_default=0, default=0)),
                ('queued_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('request', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='cases.rightsrequest')),
                ('sent_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'request_communications',
                'indexes': [models.Index(fields=['request', '-created_at'], name='idx_comm_request'), models.Index(condition=models.Q(('visible_to_subject', True)), fields=['request', '-created_at'], name='idx_comm_visible'), models.Index(condition=models.Q(('delivery_status__in', ['PENDING', 'FAILED'])), fields=['next_retry_at', 'queued_at'], name='idx_comm_pending')],
                'constraints': [models.CheckConstraint(condition=models.Q(('direction__in', ['INBOUND', 'OUTBOUND', 'SYSTEM'])), name='ck_comm_direction'), models.CheckConstraint(condition=models.Q(('channel__in', ['EMAIL', 'PORTAL', 'PHONE', 'PHYSICAL', 'OTHER'])), name='ck_comm_channel'), models.CheckConstraint(condition=models.Q(('communication_type__in', ['ACKNOWLEDGEMENT', 'ASSIGNMENT_NOTICE', 'INFORMATION_REQUEST', 'CLARIFICATION_REMINDER', 'EXTENSION_NOTICE', 'DEADLINE_ALERT', 'RESPONSE', 'REJECTION', 'ARCHIVE_NOTICE', 'CANCELLATION_NOTICE', 'PORTABILITY_READY', 'COMPLAINT_INFORMATION', 'DELIVERY_FAILURE_ALERT', 'OTHER'])), name='ck_comm_type'), models.CheckConstraint(condition=models.Q(('encryption_key_version__gt', 0)), name='ck_comm_key_version'), models.CheckConstraint(condition=models.Q(('delivery_status__in', ['PENDING', 'PROCESSING', 'SENT', 'DELIVERED', 'FAILED', 'RECEIVED', 'CANCELLED'])), name='ck_comm_status'), models.CheckConstraint(condition=models.Q(('attempt_count__gte', 0)), name='ck_comm_attempts'), models.CheckConstraint(condition=models.Q(('sent_at__isnull', True), ('sent_at__gte', models.F('created_at')), _connector='OR'), name='ck_comm_sent_at')],
            },
        ),
    ]
