# Generated by Django 5.2.16 on 2026-08-17 16:08

import apps.core.fields
import django.contrib.postgres.functions
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_database_resolution_fk_actions'),
        ('communications', '0002_database_fk_actions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortabilityExport',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_format', models.CharField(choices=[('JSON', 'JSON'), ('CSV', 'CSV')], max_length=10)),
                ('storage_backend', models.CharField(choices=[('LOCAL', 'Local'), ('S3', 'S3'), ('MINIO', 'MinIO')], db_default='LOCAL', default='LOCAL', max_length=20)),
                ('storage_key', models.TextField(unique=True)),
                ('file_sha256', apps.core.fields.FixedCharField(max_length=64)),
                ('is_encrypted', models.BooleanField(db_default=True, default=True)),
                ('encryption_key_version', models.SmallIntegerField(db_default=1, default=1)),
                ('generated_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portability_exports_generated', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='portability_exports', to='cases.rightsrequest')),
            ],
            options={
                'db_table': 'portability_exports',
                'indexes': [models.Index(fields=['request', '-generated_at'], name='idx_portability_request'), models.Index(condition=models.Q(('revoked_at__isnull', True), ('expires_at__isnull', False)), fields=['expires_at'], name='idx_portability_expiration')],
                'constraints': [models.CheckConstraint(condition=models.Q(('export_format__in', ['JSON', 'CSV'])), name='ck_port_export_format'), models.CheckConstraint(condition=models.Q(('storage_backend__in', ['LOCAL', 'S3', 'MINIO'])), name='ck_port_storage'), models.CheckConstraint(condition=models.Q(('encryption_key_version__gt', 0)), name='ck_port_key_version'), models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('generated_at')), _connector='OR'), name='ck_port_expiration'), models.CheckConstraint(condition=models.Q(('downloaded_at__isnull', True), ('downloaded_at__gte', models.F('generated_at')), _connector='OR'), name='ck_port_downloaded'), models.CheckConstraint(condition=models.Q(('revoked_at__isnull', True), ('revoked_at__gte', models.F('generated_at')), _connector='OR'), name='ck_port_revoked')],
            },
        ),
    ]
