# Generated by Django 5.2.16 on 2026-08-17 15:29

import apps.core.fields
import django.contrib.postgres.functions
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal_content', '0002_database_fk_actions'),
        ('subjects', '0002_database_fk_actions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsRequest',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('request_details_encrypted', models.BinaryField()),
                ('subject_snapshot_encrypted', models.BinaryField()),
                ('encryption_key_version', models.SmallIntegerField(db_default=1, default=1)),
                ('snapshot_key_version', models.SmallIntegerField(db_default=1, default=1)),
                ('source_channel', models.CharField(choices=[('WEB', 'Web'), ('EMAIL', 'Correo electrónico'), ('PHYSICAL', 'Físico'), ('PHONE', 'Teléfono'), ('OTHER', 'Otro')], db_default='WEB', default='WEB', max_length=20)),
                ('status', models.CharField(choices=[('RECEIVED', 'Recibida'), ('UNDER_REVIEW', 'En revisión'), ('AWAITING_INFORMATION', 'Esperando información'), ('EXTENDED', 'Extendida'), ('PARTIALLY_APPROVED', 'Aprobada parcialmente'), ('RESPONDED', 'Respondida'), ('REJECTED', 'Rechazada'), ('ARCHIVED', 'Archivada'), ('CANCELLED', 'Cancelada'), ('CLOSED', 'Cerrada')], db_default='RECEIVED', default='RECEIVED', max_length=30)),
                ('identity_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('VERIFIED', 'Verificada'), ('REJECTED', 'Rechazada'), ('REQUIRES_REVIEW', 'Requiere revisión')], db_default='PENDING', default='PENDING', max_length=20)),
                ('received_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow())),
                ('current_due_at', models.DateTimeField(blank=True, null=True)),
                ('extension_applied', models.BooleanField(db_default=False, default=False)),
                ('extension_reason_encrypted', models.BinaryField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow())),
                ('assigned_to', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('data_subject', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='rights_requests', to='subjects.datasubject')),
                ('representative', models.ForeignKey(blank=True, db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rights_requests', to='subjects.subjectrepresentative')),
                ('right', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='rights_requests', to='legal_content.rightcatalog')),
            ],
            options={
                'db_table': 'rights_requests',
            },
        ),
        migrations.CreateModel(
            name='RequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, choices=[('RECEIVED', 'Recibida'), ('UNDER_REVIEW', 'En revisión'), ('AWAITING_INFORMATION', 'Esperando información'), ('EXTENDED', 'Extendida'), ('PARTIALLY_APPROVED', 'Aprobada parcialmente'), ('RESPONDED', 'Respondida'), ('REJECTED', 'Rechazada'), ('ARCHIVED', 'Archivada'), ('CANCELLED', 'Cancelada'), ('CLOSED', 'Cerrada')], max_length=30, null=True)),
                ('new_status', models.CharField(choices=[('RECEIVED', 'Recibida'), ('UNDER_REVIEW', 'En revisión'), ('AWAITING_INFORMATION', 'Esperando información'), ('EXTENDED', 'Extendida'), ('PARTIALLY_APPROVED', 'Aprobada parcialmente'), ('RESPONDED', 'Respondida'), ('REJECTED', 'Rechazada'), ('ARCHIVED', 'Archivada'), ('CANCELLED', 'Cancelada'), ('CLOSED', 'Cerrada')], max_length=30)),
                ('notes_encrypted', models.BinaryField(blank=True, null=True)),
                ('encryption_key_version', models.SmallIntegerField(db_default=1, default=1)),
                ('change_source', models.CharField(choices=[('WEB', 'Web'), ('CELERY', 'Celery'), ('SYSTEM', 'Sistema'), ('COMMAND', 'Comando'), ('API', 'API')], db_default='WEB', default='WEB', max_length=20)),
                ('changed_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('changed_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_status_changes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='cases.rightsrequest')),
            ],
            options={
                'db_table': 'request_status_history',
            },
        ),
        migrations.CreateModel(
            name='RequestDeadline',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deadline_type', models.CharField(choices=[('INITIAL', 'Inicial'), ('EXTENSION', 'Extensión'), ('CLARIFICATION', 'Aclaración'), ('OTHER', 'Otro')], max_length=30)),
                ('sequence_number', models.SmallIntegerField(db_default=1, default=1)),
                ('starts_at', models.DateTimeField()),
                ('due_at', models.DateTimeField()),
                ('warning_at', models.DateTimeField(blank=True, null=True)),
                ('warning_sent_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('PAUSED', 'Pausado'), ('COMPLETED', 'Completado'), ('EXPIRED', 'Vencido'), ('CANCELLED', 'Cancelado')], db_default='ACTIVE', default='ACTIVE', max_length=20)),
                ('rule_snapshot', models.JSONField(db_default=models.Value({}, output_field=models.JSONField()), default=dict)),
                ('created_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('request', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='cases.rightsrequest')),
            ],
            options={
                'db_table': 'request_deadlines',
            },
        ),
        migrations.CreateModel(
            name='RequestClarification',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Solicitada'), ('RECEIVED', 'Recibida'), ('EXPIRED', 'Vencida'), ('CANCELLED', 'Cancelada')], db_default='REQUESTED', default='REQUESTED', max_length=20)),
                ('request_message_encrypted', models.BinaryField()),
                ('response_message_encrypted', models.BinaryField(blank=True, null=True)),
                ('encryption_key_version', models.SmallIntegerField(db_default=1, default=1)),
                ('deadline_effect', models.CharField(choices=[('NO_CHANGE', 'Sin cambio'), ('PAUSE', 'Pausa'), ('RESTART', 'Reinicio')], db_default='NO_CHANGE', default='NO_CHANGE', max_length=20)),
                ('deadline_effect_legal_basis', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('created_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clarifications_created', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='clarifications', to='cases.rightsrequest')),
            ],
            options={
                'db_table': 'request_clarifications',
            },
        ),
        migrations.CreateModel(
            name='RequestAccessToken',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', apps.core.fields.FixedCharField(max_length=64, unique=True)),
                ('lookup_key_version', models.SmallIntegerField(db_default=1, default=1)),
                ('purpose', models.CharField(choices=[('TRACKING', 'Seguimiento'), ('FILE_DOWNLOAD', 'Descarga de archivo'), ('PORTABILITY_DOWNLOAD', 'Descarga de portabilidad'), ('EMAIL_VERIFICATION', 'Verificación de correo')], db_default='TRACKING', default='TRACKING', max_length=30)),
                ('resource_type', models.CharField(blank=True, choices=[('ATTACHMENT', 'Adjunto'), ('PORTABILITY_EXPORT', 'Exportación de portabilidad')], max_length=30, null=True)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('failed_attempts', models.IntegerField(db_default=0, default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('request', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='cases.rightsrequest')),
            ],
            options={
                'db_table': 'request_access_tokens',
            },
        ),
        migrations.AddIndex(
            model_name='rightsrequest',
            index=models.Index(fields=['status'], name='idx_rr_status'),
        ),
        migrations.AddIndex(
            model_name='rightsrequest',
            index=models.Index(condition=models.Q(('status__in', ['RESPONDED', 'REJECTED', 'ARCHIVED', 'CANCELLED', 'CLOSED']), _negated=True), fields=['current_due_at'], name='idx_rr_due'),
        ),
        migrations.AddIndex(
            model_name='rightsrequest',
            index=models.Index(fields=['data_subject'], name='idx_rr_subject'),
        ),
        migrations.AddIndex(
            model_name='rightsrequest',
            index=models.Index(fields=['right'], name='idx_rr_right'),
        ),
        migrations.AddIndex(
            model_name='rightsrequest',
            index=models.Index(fields=['assigned_to', 'status'], name='idx_rr_assigned'),
        ),
        migrations.AddIndex(
            model_name='rightsrequest',
            index=models.Index(fields=['-received_at'], name='idx_rr_received'),
        ),
        migrations.AddConstraint(
            model_name='rightsrequest',
            constraint=models.CheckConstraint(condition=models.Q(('encryption_key_version__gt', 0)), name='ck_rr_encryption_key_version'),
        ),
        migrations.AddConstraint(
            model_name='rightsrequest',
            constraint=models.CheckConstraint(condition=models.Q(('snapshot_key_version__gt', 0)), name='ck_rr_snapshot_key_version'),
        ),
        migrations.AddConstraint(
            model_name='rightsrequest',
            constraint=models.CheckConstraint(condition=models.Q(('source_channel__in', ['WEB', 'EMAIL', 'PHYSICAL', 'PHONE', 'OTHER'])), name='ck_rr_source_channel'),
        ),
        migrations.AddConstraint(
            model_name='rightsrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['RECEIVED', 'UNDER_REVIEW', 'AWAITING_INFORMATION', 'EXTENDED', 'PARTIALLY_APPROVED', 'RESPONDED', 'REJECTED', 'ARCHIVED', 'CANCELLED', 'CLOSED'])), name='ck_rr_status'),
        ),
        migrations.AddConstraint(
            model_name='rightsrequest',
            constraint=models.CheckConstraint(condition=models.Q(('identity_status__in', ['PENDING', 'VERIFIED', 'REJECTED', 'REQUIRES_REVIEW'])), name='ck_rr_identity_status'),
        ),
        migrations.AddConstraint(
            model_name='rightsrequest',
            constraint=models.CheckConstraint(condition=models.Q(('closed_at__isnull', True), ('closed_at__gte', models.F('received_at')), _connector='OR'), name='ck_rr_closed_after_received'),
        ),
        migrations.AddConstraint(
            model_name='rightsrequest',
            constraint=models.CheckConstraint(condition=models.Q(('responded_at__isnull', True), ('responded_at__gte', models.F('received_at')), _connector='OR'), name='ck_rr_responded_after_received'),
        ),
        migrations.AddConstraint(
            model_name='rightsrequest',
            constraint=models.CheckConstraint(condition=models.Q(('extension_applied', False), ('extension_reason_encrypted__isnull', False), _connector='OR'), name='ck_rr_extension_reason'),
        ),
        migrations.AddIndex(
            model_name='requeststatushistory',
            index=models.Index(fields=['request', '-changed_at'], name='idx_rsh_request'),
        ),
        migrations.AddIndex(
            model_name='requeststatushistory',
            index=models.Index(condition=models.Q(('changed_by__isnull', False)), fields=['changed_by', '-changed_at'], name='idx_rsh_actor'),
        ),
        migrations.AddConstraint(
            model_name='requeststatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('encryption_key_version__gt', 0)), name='ck_rsh_key_version'),
        ),
        migrations.AddConstraint(
            model_name='requeststatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('change_source__in', ['WEB', 'CELERY', 'SYSTEM', 'COMMAND', 'API'])), name='ck_rsh_change_source'),
        ),
        migrations.AddIndex(
            model_name='requestdeadline',
            index=models.Index(condition=models.Q(('status', 'ACTIVE')), fields=['due_at'], name='idx_rd_active'),
        ),
        migrations.AddIndex(
            model_name='requestdeadline',
            index=models.Index(fields=['request', 'sequence_number'], name='idx_rd_request'),
        ),
        migrations.AddConstraint(
            model_name='requestdeadline',
            constraint=models.CheckConstraint(condition=models.Q(('deadline_type__in', ['INITIAL', 'EXTENSION', 'CLARIFICATION', 'OTHER'])), name='ck_rd_type'),
        ),
        migrations.AddConstraint(
            model_name='requestdeadline',
            constraint=models.CheckConstraint(condition=models.Q(('sequence_number__gt', 0)), name='ck_rd_sequence'),
        ),
        migrations.AddConstraint(
            model_name='requestdeadline',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'PAUSED', 'COMPLETED', 'EXPIRED', 'CANCELLED'])), name='ck_rd_status'),
        ),
        migrations.AddConstraint(
            model_name='requestdeadline',
            constraint=models.UniqueConstraint(fields=('request', 'deadline_type', 'sequence_number'), name='uq_rd_request_type_seq'),
        ),
        migrations.AddConstraint(
            model_name='requestdeadline',
            constraint=models.CheckConstraint(condition=models.Q(('due_at__gte', models.F('starts_at'))), name='ck_rd_due_date'),
        ),
        migrations.AddConstraint(
            model_name='requestdeadline',
            constraint=models.CheckConstraint(condition=models.Q(('warning_at__isnull', True), ('warning_at__lte', models.F('due_at')), _connector='OR'), name='ck_rd_warning_date'),
        ),
        migrations.AddConstraint(
            model_name='requestdeadline',
            constraint=models.CheckConstraint(condition=models.Q(('resumed_at__isnull', True), ('paused_at__isnull', False), _connector='OR'), name='ck_rd_resume_requires_pause'),
        ),
        migrations.AddConstraint(
            model_name='requestdeadline',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('completed_at__gte', models.F('starts_at')), _connector='OR'), name='ck_rd_completed_date'),
        ),
        migrations.AddIndex(
            model_name='requestclarification',
            index=models.Index(fields=['request', '-requested_at'], name='idx_clar_request'),
        ),
        migrations.AddConstraint(
            model_name='requestclarification',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['REQUESTED', 'RECEIVED', 'EXPIRED', 'CANCELLED'])), name='ck_clar_status'),
        ),
        migrations.AddConstraint(
            model_name='requestclarification',
            constraint=models.CheckConstraint(condition=models.Q(('encryption_key_version__gt', 0)), name='ck_clar_key_version'),
        ),
        migrations.AddConstraint(
            model_name='requestclarification',
            constraint=models.CheckConstraint(condition=models.Q(('deadline_effect__in', ['NO_CHANGE', 'PAUSE', 'RESTART'])), name='ck_clar_deadline_effect'),
        ),
        migrations.AddConstraint(
            model_name='requestclarification',
            constraint=models.CheckConstraint(condition=models.Q(('due_at__isnull', True), ('due_at__gte', models.F('requested_at')), _connector='OR'), name='ck_clar_due_date'),
        ),
        migrations.AddConstraint(
            model_name='requestclarification',
            constraint=models.CheckConstraint(condition=models.Q(('received_at__isnull', True), ('received_at__gte', models.F('requested_at')), _connector='OR'), name='ck_clar_received_date'),
        ),
        migrations.AddConstraint(
            model_name='requestclarification',
            constraint=models.CheckConstraint(condition=models.Q(('deadline_effect', 'NO_CHANGE'), ('deadline_effect_legal_basis__isnull', False), _connector='OR'), name='ck_clar_legal_basis'),
        ),
        migrations.AddIndex(
            model_name='requestaccesstoken',
            index=models.Index(fields=['request', 'purpose'], name='idx_rat_request'),
        ),
        migrations.AddIndex(
            model_name='requestaccesstoken',
            index=models.Index(condition=models.Q(('revoked_at__isnull', True)), fields=['expires_at'], name='idx_rat_expiration'),
        ),
        migrations.AddConstraint(
            model_name='requestaccesstoken',
            constraint=models.CheckConstraint(condition=models.Q(('lookup_key_version__gt', 0)), name='ck_rat_lookup_key_version'),
        ),
        migrations.AddConstraint(
            model_name='requestaccesstoken',
            constraint=models.CheckConstraint(condition=models.Q(('purpose__in', ['TRACKING', 'FILE_DOWNLOAD', 'PORTABILITY_DOWNLOAD', 'EMAIL_VERIFICATION'])), name='ck_rat_purpose'),
        ),
        migrations.AddConstraint(
            model_name='requestaccesstoken',
            constraint=models.CheckConstraint(condition=models.Q(('resource_type__isnull', True), ('resource_type__in', ['ATTACHMENT', 'PORTABILITY_EXPORT']), _connector='OR'), name='ck_rat_resource_type'),
        ),
        migrations.AddConstraint(
            model_name='requestaccesstoken',
            constraint=models.CheckConstraint(condition=models.Q(('failed_attempts__gte', 0)), name='ck_rat_failed_attempts'),
        ),
        migrations.AddConstraint(
            model_name='requestaccesstoken',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='ck_rat_expiration'),
        ),
        migrations.AddConstraint(
            model_name='requestaccesstoken',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purpose', 'FILE_DOWNLOAD'), ('resource_id__isnull', False), ('resource_type', 'ATTACHMENT')), models.Q(('purpose', 'PORTABILITY_DOWNLOAD'), ('resource_id__isnull', False), ('resource_type', 'PORTABILITY_EXPORT')), models.Q(('purpose__in', ['TRACKING', 'EMAIL_VERIFICATION']), ('resource_type__isnull', True), ('resource_id__isnull', True)), _connector='OR'), name='ck_rat_resource_binding'),
        ),
    ]
