# Generated by Django 5.2.16 on 2026-08-17 16:02

import django.contrib.postgres.functions
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_database_objects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseOutcomeReason',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_type', models.CharField(choices=[('REJECTION', 'Rechazo'), ('ARCHIVE', 'Archivo'), ('CANCELLATION', 'Cancelación')], max_length=20)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, null=True)),
                ('legal_basis', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
            ],
            options={
                'db_table': 'case_outcome_reasons',
                'ordering': ['reason_type', 'code'],
                'indexes': [models.Index(condition=models.Q(('is_active', True)), fields=['reason_type', 'code'], name='idx_cor_type_active')],
                'constraints': [models.CheckConstraint(condition=models.Q(('reason_type__in', ['REJECTION', 'ARCHIVE', 'CANCELLATION'])), name='ck_cor_reason_type'), models.UniqueConstraint(fields=('reason_type', 'code'), name='uq_cor_type_code')],
            },
        ),
        migrations.CreateModel(
            name='RequestResolution',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resolution_type', models.CharField(choices=[('APPROVED', 'Aprobada'), ('PARTIALLY_APPROVED', 'Aprobada parcialmente'), ('REJECTED', 'Rechazada'), ('ARCHIVED', 'Archivada'), ('CANCELLED', 'Cancelada')], max_length=30)),
                ('legal_basis', models.TextField(blank=True, null=True)),
                ('resolution_details_encrypted', models.BinaryField()),
                ('encryption_key_version', models.SmallIntegerField(db_default=1, default=1)),
                ('resolved_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('outcome_reason', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='resolutions', to='cases.caseoutcomereason')),
                ('request', models.OneToOneField(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='cases.rightsrequest')),
                ('resolved_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='requests_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'request_resolutions',
                'indexes': [models.Index(fields=['resolved_by', '-resolved_at'], name='idx_resolution_actor')],
                'constraints': [models.CheckConstraint(condition=models.Q(('resolution_type__in', ['APPROVED', 'PARTIALLY_APPROVED', 'REJECTED', 'ARCHIVED', 'CANCELLED'])), name='ck_resolution_type'), models.CheckConstraint(condition=models.Q(('encryption_key_version__gt', 0)), name='ck_resolution_key_version'), models.CheckConstraint(condition=models.Q(models.Q(('resolution_type__in', ['REJECTED', 'ARCHIVED', 'CANCELLED']), _negated=True), ('outcome_reason__isnull', False), _connector='OR'), name='ck_resolution_reason_required')],
            },
        ),
    ]
