# Generated by Django 5.2.16 on 2026-10-02 04:58

import django.contrib.postgres.functions
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_database_resolution_fk_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicIntakeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_intake_submissions', to='cases.rightsrequest')),
            ],
            options={
                'db_table': 'public_intake_submissions',
                'indexes': [models.Index(fields=['created_at'], name='idx_public_intake_created'), models.Index(fields=['request'], name='idx_public_intake_request')],
            },
        ),
    ]
