# Generated by Django 5.2.16 on 2026-08-17 15:20

import apps.core.fields
import django.contrib.postgres.functions
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSubject',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('EMPLOYEE', 'Empleado'), ('CANDIDATE', 'Candidato'), ('CUSTOMER', 'Cliente'), ('VENDOR', 'Vendedor'), ('SUPPLIER', 'Proveedor'), ('FORMER_EMPLOYEE', 'Exempleado'), ('OTHER', 'Otro')], max_length=30)),
                ('document_type', models.CharField(choices=[('CEDULA', 'Cédula'), ('RUC', 'RUC'), ('PASSPORT', 'Pasaporte'), ('OTHER', 'Otro')], max_length=20)),
                ('document_number_encrypted', models.BinaryField()),
                ('document_number_lookup_hash', apps.core.fields.FixedCharField(max_length=64, unique=True)),
                ('full_name_encrypted', models.BinaryField()),
                ('email_encrypted', models.BinaryField()),
                ('email_lookup_hash', apps.core.fields.FixedCharField(max_length=64)),
                ('phone_encrypted', models.BinaryField(blank=True, null=True)),
                ('encryption_key_version', models.SmallIntegerField(db_default=1, default=1)),
                ('lookup_key_version', models.SmallIntegerField(db_default=1, default=1)),
                ('created_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow())),
            ],
            options={
                'db_table': 'data_subjects',
                'indexes': [models.Index(fields=['email_lookup_hash'], name='idx_ds_email_lookup')],
                'constraints': [models.CheckConstraint(condition=models.Q(('subject_type__in', ['EMPLOYEE', 'CANDIDATE', 'CUSTOMER', 'VENDOR', 'SUPPLIER', 'FORMER_EMPLOYEE', 'OTHER'])), name='ck_data_subjects_subject_type'), models.CheckConstraint(condition=models.Q(('document_type__in', ['CEDULA', 'RUC', 'PASSPORT', 'OTHER'])), name='ck_data_subjects_document_type'), models.CheckConstraint(condition=models.Q(('encryption_key_version__gt', 0)), name='ck_data_subjects_encryption_key_version'), models.CheckConstraint(condition=models.Q(('lookup_key_version__gt', 0)), name='ck_data_subjects_lookup_key_version')],
            },
        ),
        migrations.CreateModel(
            name='SubjectRepresentative',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('representative_name_encrypted', models.BinaryField()),
                ('representative_document_type', models.CharField(choices=[('CEDULA', 'Cédula'), ('RUC', 'RUC'), ('PASSPORT', 'Pasaporte'), ('OTHER', 'Otro')], max_length=20)),
                ('representative_document_encrypted', models.BinaryField()),
                ('representative_document_lookup_hash', apps.core.fields.FixedCharField(max_length=64)),
                ('representative_email_encrypted', models.BinaryField(blank=True, null=True)),
                ('encryption_key_version', models.SmallIntegerField(db_default=1, default=1)),
                ('lookup_key_version', models.SmallIntegerField(db_default=1, default=1)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('VERIFIED', 'Verificado'), ('REJECTED', 'Rechazado')], db_default='PENDING', default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('data_subject', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='subjects.datasubject')),
                ('verified_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representatives_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subject_representatives',
                'indexes': [models.Index(fields=['data_subject'], name='idx_representatives_subject'), models.Index(fields=['representative_document_lookup_hash'], name='idx_rep_doc_lookup')],
                'constraints': [models.CheckConstraint(condition=models.Q(('representative_document_type__in', ['CEDULA', 'RUC', 'PASSPORT', 'OTHER'])), name='ck_representative_document_type'), models.CheckConstraint(condition=models.Q(('encryption_key_version__gt', 0)), name='ck_representative_encryption_key_version'), models.CheckConstraint(condition=models.Q(('lookup_key_version__gt', 0)), name='ck_representative_lookup_key_version'), models.CheckConstraint(condition=models.Q(('verification_status__in', ['PENDING', 'VERIFIED', 'REJECTED'])), name='ck_representative_verification_status'), models.CheckConstraint(condition=models.Q(models.Q(('verification_status', 'VERIFIED'), _negated=True), ('verified_at__isnull', False), _connector='OR'), name='ck_representative_verified_timestamp'), models.UniqueConstraint(fields=('id', 'data_subject'), name='uq_representative_id_subject'), models.UniqueConstraint(fields=('data_subject', 'representative_document_lookup_hash'), name='uq_representative_subject_document')],
            },
        ),
    ]
