# Generated by Django 5.2.16 on 2026-08-17 16:13

import apps.core.fields
import django.contrib.postgres.functions
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHoliday',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holiday_date', models.DateField(unique=True)),
                ('description', models.CharField(max_length=180)),
                ('is_national', models.BooleanField(db_default=False, default=False)),
            ],
            options={
                'db_table': 'business_holidays',
                'ordering': ['holiday_date'],
            },
        ),
        migrations.CreateModel(
            name='RetentionRule',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50, unique=True)),
                ('retention_days', models.IntegerField()),
                ('retention_anchor', models.CharField(choices=[('CREATED_AT', 'Fecha de creación'), ('RECEIVED_AT', 'Fecha de recepción'), ('CLOSED_AT', 'Fecha de cierre'), ('EXPIRES_AT', 'Fecha de expiración'), ('REVOKED_AT', 'Fecha de revocación'), ('LAST_ACTIVITY_AT', 'Última actividad')], max_length=30)),
                ('final_action', models.CharField(choices=[('DELETE', 'Eliminar'), ('ANONYMIZE', 'Anonimizar'), ('BLOCK', 'Bloquear'), ('ARCHIVE', 'Archivar')], max_length=20)),
                ('requires_approval', models.BooleanField(db_default=True, default=True)),
                ('legal_basis', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('created_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow())),
            ],
            options={
                'db_table': 'retention_rules',
                'constraints': [models.CheckConstraint(condition=models.Q(('retention_days__gt', 0)), name='ck_retention_days'), models.CheckConstraint(condition=models.Q(('retention_anchor__in', ['CREATED_AT', 'RECEIVED_AT', 'CLOSED_AT', 'EXPIRES_AT', 'REVOKED_AT', 'LAST_ACTIVITY_AT'])), name='ck_retention_anchor'), models.CheckConstraint(condition=models.Q(('final_action__in', ['DELETE', 'ANONYMIZE', 'BLOCK', 'ARCHIVE'])), name='ck_retention_action')],
            },
        ),
        migrations.CreateModel(
            name='DataDisposalEvent',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_pk', models.TextField()),
                ('action', models.CharField(choices=[('DELETE', 'Eliminar'), ('ANONYMIZE', 'Anonimizar'), ('BLOCK', 'Bloquear'), ('ARCHIVE', 'Archivar')], max_length=20)),
                ('status', models.CharField(choices=[('DETECTED', 'Detectado'), ('PENDING_APPROVAL', 'Pendiente de aprobación'), ('APPROVED', 'Aprobado'), ('EXECUTED', 'Ejecutado'), ('REJECTED', 'Rechazado'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado')], db_default='DETECTED', default='DETECTED', max_length=30)),
                ('detected_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes_encrypted', models.BinaryField(blank=True, null=True)),
                ('encryption_key_version', models.SmallIntegerField(db_default=1, default=1)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_sha256', apps.core.fields.FixedCharField(blank=True, max_length=64, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('approved_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposal_events_approved', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposal_events_executed', to=settings.AUTH_USER_MODEL)),
                ('retention_rule', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposal_events', to='retention.retentionrule')),
            ],
            options={
                'db_table': 'data_disposal_events',
                'indexes': [models.Index(condition=models.Q(('status__in', ['DETECTED', 'PENDING_APPROVAL', 'APPROVED'])), fields=['status', 'detected_at'], name='idx_disposal_pending'), models.Index(condition=models.Q(('retention_rule__isnull', False)), fields=['retention_rule'], name='idx_disposal_rule')],
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ['DELETE', 'ANONYMIZE', 'BLOCK', 'ARCHIVE'])), name='ck_disposal_action'), models.CheckConstraint(condition=models.Q(('status__in', ['DETECTED', 'PENDING_APPROVAL', 'APPROVED', 'EXECUTED', 'REJECTED', 'FAILED', 'CANCELLED'])), name='ck_disposal_status'), models.CheckConstraint(condition=models.Q(('encryption_key_version__gt', 0)), name='ck_disposal_key_version'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), ('approved_at__isnull', False), _connector='OR'), name='ck_disposal_approved'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'EXECUTED'), _negated=True), ('executed_at__isnull', False), _connector='OR'), name='ck_disposal_executed'), models.CheckConstraint(condition=models.Q(('approved_at__isnull', True), ('approved_at__gte', models.F('detected_at')), _connector='OR'), name='ck_disposal_approval_date'), models.CheckConstraint(condition=models.Q(('executed_at__isnull', True), ('executed_at__gte', models.F('detected_at')), _connector='OR'), name='ck_disposal_execution_date'), models.UniqueConstraint(condition=models.Q(('status__in', ['DETECTED', 'PENDING_APPROVAL', 'APPROVED'])), fields=('entity_type', 'entity_pk', 'action'), name='uq_disposal_open_event')],
            },
        ),
    ]
