# Generated by Django 5.2.16 on 2026-08-17 16:17

import apps.core.fields
import django.contrib.postgres.functions
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('USER', 'Usuario'), ('SYSTEM', 'Sistema')], db_default='USER', default='USER', max_length=10)),
                ('source', models.CharField(choices=[('WEB', 'Web'), ('API', 'API'), ('CELERY', 'Celery'), ('SIGNAL', 'Signal'), ('COMMAND', 'Comando'), ('SYSTEM', 'Sistema')], db_default='WEB', default='WEB', max_length=20)),
                ('correlation_id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_pk', models.TextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('reason_encrypted', models.BinaryField(blank=True, null=True)),
                ('encryption_key_version', models.SmallIntegerField(db_default=1, default=1)),
                ('previous_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(db_default=models.Value({}, output_field=models.JSONField()), default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('chain_scope', models.CharField(db_default='GLOBAL', default='GLOBAL', max_length=50)),
                ('chain_position', models.BigIntegerField()),
                ('previous_hash', apps.core.fields.FixedCharField(blank=True, max_length=64, null=True)),
                ('entry_hash', apps.core.fields.FixedCharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('actor_user', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['-created_at'], name='idx_audit_created_at'), models.Index(fields=['entity_type', 'entity_pk', '-created_at'], name='idx_audit_entity'), models.Index(fields=['correlation_id'], name='idx_audit_correlation'), models.Index(condition=models.Q(('actor_user__isnull', False)), fields=['actor_user', '-created_at'], name='idx_audit_actor')],
                'constraints': [models.CheckConstraint(condition=models.Q(('actor_type__in', ['USER', 'SYSTEM'])), name='ck_audit_actor_type'), models.CheckConstraint(condition=models.Q(('source__in', ['WEB', 'API', 'CELERY', 'SIGNAL', 'COMMAND', 'SYSTEM'])), name='ck_audit_source'), models.CheckConstraint(condition=models.Q(('encryption_key_version__gt', 0)), name='ck_audit_key_version'), models.CheckConstraint(condition=models.Q(('actor_type', 'SYSTEM'), ('actor_user__isnull', False), _connector='OR'), name='ck_audit_actor_user'), models.CheckConstraint(condition=models.Q(('chain_position__gt', 0)), name='ck_audit_chain_position'), models.CheckConstraint(condition=models.Q(models.Q(('chain_position', 1), _negated=True), ('previous_hash__isnull', True), _connector='OR'), name='ck_audit_first_hash'), models.UniqueConstraint(fields=('chain_scope', 'chain_position'), name='uq_audit_chain_position')],
            },
        ),
    ]
