--
-- PostgreSQL database dump
--

\restrict 1HsGSfMaVpoxD8lEj2dSxNiQkgnL2gi1YTwjHf2fhcZDRgPt6nvpQXzlq3jQB1w

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: citext; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;


--
-- Name: EXTENSION citext; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    actor_type character varying(10) DEFAULT 'USER'::character varying NOT NULL,
    source character varying(20) DEFAULT 'WEB'::character varying NOT NULL,
    correlation_id uuid DEFAULT gen_random_uuid() NOT NULL,
    action character varying(100) NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_pk text,
    description character varying(500),
    reason_encrypted bytea,
    encryption_key_version smallint DEFAULT 1 NOT NULL,
    previous_values jsonb,
    new_values jsonb,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    ip_address inet,
    user_agent character varying(500),
    chain_scope character varying(50) DEFAULT 'GLOBAL'::character varying NOT NULL,
    chain_position bigint NOT NULL,
    previous_hash character(64),
    entry_hash character(64) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    actor_user_id uuid,
    CONSTRAINT ck_audit_actor_type CHECK (((actor_type)::text = ANY ((ARRAY['USER'::character varying, 'SYSTEM'::character varying])::text[]))),
    CONSTRAINT ck_audit_actor_user CHECK ((((actor_type)::text = 'SYSTEM'::text) OR (actor_user_id IS NOT NULL))),
    CONSTRAINT ck_audit_chain_position CHECK ((chain_position > 0)),
    CONSTRAINT ck_audit_first_hash CHECK (((NOT (chain_position = 1)) OR (previous_hash IS NULL))),
    CONSTRAINT ck_audit_key_version CHECK ((encryption_key_version > 0)),
    CONSTRAINT ck_audit_source CHECK (((source)::text = ANY ((ARRAY['WEB'::character varying, 'API'::character varying, 'CELERY'::character varying, 'SIGNAL'::character varying, 'COMMAND'::character varying, 'SYSTEM'::character varying])::text[])))
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: business_holidays; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.business_holidays (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    holiday_date date NOT NULL,
    description character varying(180) NOT NULL,
    is_national boolean DEFAULT false NOT NULL
);


--
-- Name: case_outcome_reasons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.case_outcome_reasons (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    reason_type character varying(20) NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(180) NOT NULL,
    description text,
    legal_basis character varying(250),
    is_active boolean DEFAULT true NOT NULL,
    CONSTRAINT ck_cor_reason_type CHECK (((reason_type)::text = ANY ((ARRAY['REJECTION'::character varying, 'ARCHIVE'::character varying, 'CANCELLATION'::character varying])::text[])))
);


--
-- Name: data_disposal_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.data_disposal_events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_pk text NOT NULL,
    action character varying(20) NOT NULL,
    status character varying(30) DEFAULT 'DETECTED'::character varying NOT NULL,
    detected_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    approved_at timestamp with time zone,
    approval_notes_encrypted bytea,
    encryption_key_version smallint DEFAULT 1 NOT NULL,
    executed_at timestamp with time zone,
    evidence_sha256 character(64),
    error_code character varying(80),
    error_message character varying(500),
    approved_by_id uuid,
    executed_by_id uuid,
    retention_rule_id uuid,
    CONSTRAINT ck_disposal_action CHECK (((action)::text = ANY ((ARRAY['DELETE'::character varying, 'ANONYMIZE'::character varying, 'BLOCK'::character varying, 'ARCHIVE'::character varying])::text[]))),
    CONSTRAINT ck_disposal_approval_date CHECK (((approved_at IS NULL) OR (approved_at >= detected_at))),
    CONSTRAINT ck_disposal_approved CHECK (((NOT ((status)::text = 'APPROVED'::text)) OR (approved_at IS NOT NULL))),
    CONSTRAINT ck_disposal_executed CHECK (((NOT ((status)::text = 'EXECUTED'::text)) OR (executed_at IS NOT NULL))),
    CONSTRAINT ck_disposal_execution_date CHECK (((executed_at IS NULL) OR (executed_at >= detected_at))),
    CONSTRAINT ck_disposal_key_version CHECK ((encryption_key_version > 0)),
    CONSTRAINT ck_disposal_status CHECK (((status)::text = ANY ((ARRAY['DETECTED'::character varying, 'PENDING_APPROVAL'::character varying, 'APPROVED'::character varying, 'EXECUTED'::character varying, 'REJECTED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: data_subjects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.data_subjects (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    subject_type character varying(30) NOT NULL,
    document_type character varying(20) NOT NULL,
    document_number_encrypted bytea NOT NULL,
    document_number_lookup_hash character(64) NOT NULL,
    full_name_encrypted bytea NOT NULL,
    email_encrypted bytea NOT NULL,
    email_lookup_hash character(64) NOT NULL,
    phone_encrypted bytea,
    encryption_key_version smallint DEFAULT 1 NOT NULL,
    lookup_key_version smallint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_data_subjects_document_type CHECK (((document_type)::text = ANY ((ARRAY['CEDULA'::character varying, 'RUC'::character varying, 'PASSPORT'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT ck_data_subjects_encryption_key_version CHECK ((encryption_key_version > 0)),
    CONSTRAINT ck_data_subjects_lookup_key_version CHECK ((lookup_key_version > 0)),
    CONSTRAINT ck_data_subjects_subject_type CHECK (((subject_type)::text = ANY ((ARRAY['EMPLOYEE'::character varying, 'CANDIDATE'::character varying, 'CUSTOMER'::character varying, 'VENDOR'::character varying, 'SUPPLIER'::character varying, 'FORMER_EMPLOYEE'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: identity_verifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.identity_verifications (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    verification_method character varying(40) NOT NULL,
    result character varying(20) NOT NULL,
    validation_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    validation_notes_encrypted bytea,
    encryption_key_version smallint DEFAULT 1 NOT NULL,
    verified_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    request_id uuid NOT NULL,
    verified_by_id uuid,
    CONSTRAINT ck_idv_key_version CHECK ((encryption_key_version > 0)),
    CONSTRAINT ck_idv_method CHECK (((verification_method)::text = ANY ((ARRAY['STRUCTURAL_DOCUMENT_CHECK'::character varying, 'EMAIL_CODE'::character varying, 'DOCUMENT_REVIEW'::character varying, 'IN_PERSON'::character varying, 'MANUAL'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT ck_idv_result CHECK (((result)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying, 'INCONCLUSIVE'::character varying])::text[]))),
    CONSTRAINT ck_idv_verified_at CHECK ((((result)::text = 'PENDING'::text) OR (verified_at IS NOT NULL)))
);


--
-- Name: legal_documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.legal_documents (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    document_type character varying(50) NOT NULL,
    title character varying(250) NOT NULL,
    slug character varying(180) NOT NULL,
    version character varying(30) NOT NULL,
    content_html text NOT NULL,
    content_sha256 character(64) NOT NULL,
    effective_from timestamp with time zone NOT NULL,
    effective_to timestamp with time zone,
    is_published boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by_id uuid,
    CONSTRAINT ck_legal_document_effective_dates CHECK (((effective_to IS NULL) OR (effective_to > effective_from))),
    CONSTRAINT ck_legal_document_type_valid CHECK (((document_type)::text = ANY ((ARRAY['PRIVACY_POLICY'::character varying, 'EMPLOYEE_NOTICE'::character varying, 'CANDIDATE_NOTICE'::character varying, 'CUSTOMER_VENDOR_NOTICE'::character varying, 'SUPPLIER_NOTICE'::character varying, 'VIDEO_SURVEILLANCE_NOTICE'::character varying, 'RIGHTS_NOTICE'::character varying, 'COOKIES_POLICY'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: mfa_devices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mfa_devices (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    device_name character varying(100) NOT NULL,
    device_type character varying(20) DEFAULT 'TOTP'::character varying NOT NULL,
    secret_encrypted bytea NOT NULL,
    encryption_key_version smallint DEFAULT 1 NOT NULL,
    is_confirmed boolean DEFAULT false NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    confirmed_at timestamp with time zone,
    last_used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    revoked_at timestamp with time zone,
    user_id uuid NOT NULL,
    CONSTRAINT ck_mfa_confirmed_timestamp CHECK (((NOT is_confirmed) OR (confirmed_at IS NOT NULL))),
    CONSTRAINT ck_mfa_device_type_valid CHECK (((device_type)::text = ANY ((ARRAY['TOTP'::character varying, 'RECOVERY_CODES'::character varying])::text[]))),
    CONSTRAINT ck_mfa_key_version_positive CHECK ((encryption_key_version > 0)),
    CONSTRAINT ck_mfa_revoked_after_created CHECK (((revoked_at IS NULL) OR (revoked_at >= created_at)))
);


--
-- Name: notice_deliveries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notice_deliveries (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    delivery_channel character varying(20) DEFAULT 'WEB'::character varying NOT NULL,
    delivered_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    acknowledged boolean DEFAULT false NOT NULL,
    acknowledged_at timestamp with time zone,
    ip_address inet,
    user_agent character varying(500),
    rendered_content_sha256 character(64) NOT NULL,
    legal_document_id uuid NOT NULL,
    request_id uuid NOT NULL,
    CONSTRAINT ck_notice_ack CHECK (((NOT acknowledged) OR (acknowledged_at IS NOT NULL))),
    CONSTRAINT ck_notice_channel CHECK (((delivery_channel)::text = ANY ((ARRAY['WEB'::character varying, 'EMAIL'::character varying, 'PHYSICAL'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: portability_exports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.portability_exports (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    export_format character varying(10) NOT NULL,
    storage_backend character varying(20) DEFAULT 'LOCAL'::character varying NOT NULL,
    storage_key text NOT NULL,
    file_sha256 character(64) NOT NULL,
    is_encrypted boolean DEFAULT true NOT NULL,
    encryption_key_version smallint DEFAULT 1 NOT NULL,
    generated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at timestamp with time zone,
    downloaded_at timestamp with time zone,
    revoked_at timestamp with time zone,
    generated_by_id uuid,
    request_id uuid NOT NULL,
    CONSTRAINT ck_port_downloaded CHECK (((downloaded_at IS NULL) OR (downloaded_at >= generated_at))),
    CONSTRAINT ck_port_expiration CHECK (((expires_at IS NULL) OR (expires_at > generated_at))),
    CONSTRAINT ck_port_export_format CHECK (((export_format)::text = ANY ((ARRAY['JSON'::character varying, 'CSV'::character varying])::text[]))),
    CONSTRAINT ck_port_key_version CHECK ((encryption_key_version > 0)),
    CONSTRAINT ck_port_revoked CHECK (((revoked_at IS NULL) OR (revoked_at >= generated_at))),
    CONSTRAINT ck_port_storage CHECK (((storage_backend)::text = ANY ((ARRAY['LOCAL'::character varying, 'S3'::character varying, 'MINIO'::character varying])::text[])))
);


--
-- Name: request_access_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.request_access_tokens (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    token_hash character(64) NOT NULL,
    lookup_key_version smallint DEFAULT 1 NOT NULL,
    purpose character varying(30) DEFAULT 'TRACKING'::character varying NOT NULL,
    resource_type character varying(30),
    resource_id uuid,
    expires_at timestamp with time zone NOT NULL,
    failed_attempts integer DEFAULT 0 NOT NULL,
    locked_until timestamp with time zone,
    last_used_at timestamp with time zone,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    request_id uuid NOT NULL,
    CONSTRAINT ck_rat_expiration CHECK ((expires_at > created_at)),
    CONSTRAINT ck_rat_failed_attempts CHECK ((failed_attempts >= 0)),
    CONSTRAINT ck_rat_lookup_key_version CHECK ((lookup_key_version > 0)),
    CONSTRAINT ck_rat_purpose CHECK (((purpose)::text = ANY ((ARRAY['TRACKING'::character varying, 'FILE_DOWNLOAD'::character varying, 'PORTABILITY_DOWNLOAD'::character varying, 'EMAIL_VERIFICATION'::character varying])::text[]))),
    CONSTRAINT ck_rat_resource_binding CHECK (((((purpose)::text = 'FILE_DOWNLOAD'::text) AND (resource_id IS NOT NULL) AND ((resource_type)::text = 'ATTACHMENT'::text)) OR (((purpose)::text = 'PORTABILITY_DOWNLOAD'::text) AND (resource_id IS NOT NULL) AND ((resource_type)::text = 'PORTABILITY_EXPORT'::text)) OR (((purpose)::text = ANY ((ARRAY['TRACKING'::character varying, 'EMAIL_VERIFICATION'::character varying])::text[])) AND (resource_type IS NULL) AND (resource_id IS NULL)))),
    CONSTRAINT ck_rat_resource_type CHECK (((resource_type IS NULL) OR ((resource_type)::text = ANY ((ARRAY['ATTACHMENT'::character varying, 'PORTABILITY_EXPORT'::character varying])::text[]))))
);


--
-- Name: request_attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.request_attachments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    attachment_type character varying(40) NOT NULL,
    visibility character varying(20) DEFAULT 'INTERNAL'::character varying NOT NULL,
    original_filename_encrypted bytea NOT NULL,
    storage_backend character varying(20) DEFAULT 'LOCAL'::character varying NOT NULL,
    storage_key text NOT NULL,
    mime_type character varying(120) NOT NULL,
    size_bytes bigint NOT NULL,
    file_sha256 character(64) NOT NULL,
    is_encrypted boolean DEFAULT true NOT NULL,
    encryption_key_version smallint DEFAULT 1 NOT NULL,
    malware_scan_status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    uploaded_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp with time zone,
    representative_id uuid,
    request_id uuid NOT NULL,
    uploaded_by_id uuid,
    CONSTRAINT ck_att_key_version CHECK ((encryption_key_version > 0)),
    CONSTRAINT ck_att_scan_status CHECK (((malware_scan_status)::text = ANY ((ARRAY['PENDING'::character varying, 'CLEAN'::character varying, 'INFECTED'::character varying, 'FAILED'::character varying, 'NOT_APPLICABLE'::character varying])::text[]))),
    CONSTRAINT ck_att_size CHECK ((size_bytes > 0)),
    CONSTRAINT ck_att_storage CHECK (((storage_backend)::text = ANY ((ARRAY['LOCAL'::character varying, 'S3'::character varying, 'MINIO'::character varying])::text[]))),
    CONSTRAINT ck_att_type CHECK (((attachment_type)::text = ANY ((ARRAY['IDENTITY_DOCUMENT'::character varying, 'AUTHORITY_DOCUMENT'::character varying, 'SUPPORTING_DOCUMENT'::character varying, 'REQUEST_DOCUMENT'::character varying, 'RESPONSE_DOCUMENT'::character varying, 'PORTABILITY_EXPORT'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT ck_att_visibility CHECK (((visibility)::text = ANY ((ARRAY['INTERNAL'::character varying, 'SUBJECT'::character varying])::text[])))
);


--
-- Name: request_clarifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.request_clarifications (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    requested_at timestamp with time zone NOT NULL,
    due_at timestamp with time zone,
    received_at timestamp with time zone,
    status character varying(20) DEFAULT 'REQUESTED'::character varying NOT NULL,
    request_message_encrypted bytea NOT NULL,
    response_message_encrypted bytea,
    encryption_key_version smallint DEFAULT 1 NOT NULL,
    deadline_effect character varying(20) DEFAULT 'NO_CHANGE'::character varying NOT NULL,
    deadline_effect_legal_basis text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by_id uuid,
    request_id uuid NOT NULL,
    CONSTRAINT ck_clar_deadline_effect CHECK (((deadline_effect)::text = ANY ((ARRAY['NO_CHANGE'::character varying, 'PAUSE'::character varying, 'RESTART'::character varying])::text[]))),
    CONSTRAINT ck_clar_due_date CHECK (((due_at IS NULL) OR (due_at >= requested_at))),
    CONSTRAINT ck_clar_key_version CHECK ((encryption_key_version > 0)),
    CONSTRAINT ck_clar_legal_basis CHECK ((((deadline_effect)::text = 'NO_CHANGE'::text) OR (deadline_effect_legal_basis IS NOT NULL))),
    CONSTRAINT ck_clar_received_date CHECK (((received_at IS NULL) OR (received_at >= requested_at))),
    CONSTRAINT ck_clar_status CHECK (((status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'RECEIVED'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: request_communications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.request_communications (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    direction character varying(10) NOT NULL,
    channel character varying(20) NOT NULL,
    communication_type character varying(40) NOT NULL,
    visible_to_subject boolean DEFAULT false NOT NULL,
    recipient_encrypted bytea,
    subject_encrypted bytea,
    body_encrypted bytea,
    encryption_key_version smallint DEFAULT 1 NOT NULL,
    idempotency_key uuid DEFAULT gen_random_uuid() NOT NULL,
    provider_message_id character varying(255),
    delivery_status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    attempt_count integer DEFAULT 0 NOT NULL,
    queued_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_attempt_at timestamp with time zone,
    next_retry_at timestamp with time zone,
    last_error character varying(500),
    sent_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    request_id uuid NOT NULL,
    sent_by_id uuid,
    CONSTRAINT ck_comm_attempts CHECK ((attempt_count >= 0)),
    CONSTRAINT ck_comm_channel CHECK (((channel)::text = ANY ((ARRAY['EMAIL'::character varying, 'PORTAL'::character varying, 'PHONE'::character varying, 'PHYSICAL'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT ck_comm_direction CHECK (((direction)::text = ANY ((ARRAY['INBOUND'::character varying, 'OUTBOUND'::character varying, 'SYSTEM'::character varying])::text[]))),
    CONSTRAINT ck_comm_key_version CHECK ((encryption_key_version > 0)),
    CONSTRAINT ck_comm_sent_at CHECK (((sent_at IS NULL) OR (sent_at >= created_at))),
    CONSTRAINT ck_comm_status CHECK (((delivery_status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'SENT'::character varying, 'DELIVERED'::character varying, 'FAILED'::character varying, 'RECEIVED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT ck_comm_type CHECK (((communication_type)::text = ANY ((ARRAY['ACKNOWLEDGEMENT'::character varying, 'ASSIGNMENT_NOTICE'::character varying, 'INFORMATION_REQUEST'::character varying, 'CLARIFICATION_REMINDER'::character varying, 'EXTENSION_NOTICE'::character varying, 'DEADLINE_ALERT'::character varying, 'RESPONSE'::character varying, 'REJECTION'::character varying, 'ARCHIVE_NOTICE'::character varying, 'CANCELLATION_NOTICE'::character varying, 'PORTABILITY_READY'::character varying, 'COMPLAINT_INFORMATION'::character varying, 'DELIVERY_FAILURE_ALERT'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: request_deadlines; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.request_deadlines (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    deadline_type character varying(30) NOT NULL,
    sequence_number smallint DEFAULT 1 NOT NULL,
    starts_at timestamp with time zone NOT NULL,
    due_at timestamp with time zone NOT NULL,
    warning_at timestamp with time zone,
    warning_sent_at timestamp with time zone,
    paused_at timestamp with time zone,
    resumed_at timestamp with time zone,
    completed_at timestamp with time zone,
    status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    rule_snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    request_id uuid NOT NULL,
    CONSTRAINT ck_rd_completed_date CHECK (((completed_at IS NULL) OR (completed_at >= starts_at))),
    CONSTRAINT ck_rd_due_date CHECK ((due_at >= starts_at)),
    CONSTRAINT ck_rd_resume_requires_pause CHECK (((resumed_at IS NULL) OR (paused_at IS NOT NULL))),
    CONSTRAINT ck_rd_sequence CHECK ((sequence_number > 0)),
    CONSTRAINT ck_rd_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'PAUSED'::character varying, 'COMPLETED'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT ck_rd_type CHECK (((deadline_type)::text = ANY ((ARRAY['INITIAL'::character varying, 'EXTENSION'::character varying, 'CLARIFICATION'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT ck_rd_warning_date CHECK (((warning_at IS NULL) OR (warning_at <= due_at)))
);


--
-- Name: request_resolutions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.request_resolutions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    resolution_type character varying(30) NOT NULL,
    legal_basis text,
    resolution_details_encrypted bytea NOT NULL,
    encryption_key_version smallint DEFAULT 1 NOT NULL,
    resolved_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    outcome_reason_id uuid,
    request_id uuid NOT NULL,
    resolved_by_id uuid NOT NULL,
    CONSTRAINT ck_resolution_key_version CHECK ((encryption_key_version > 0)),
    CONSTRAINT ck_resolution_reason_required CHECK (((NOT ((resolution_type)::text = ANY ((ARRAY['REJECTED'::character varying, 'ARCHIVED'::character varying, 'CANCELLED'::character varying])::text[]))) OR (outcome_reason_id IS NOT NULL))),
    CONSTRAINT ck_resolution_type CHECK (((resolution_type)::text = ANY ((ARRAY['APPROVED'::character varying, 'PARTIALLY_APPROVED'::character varying, 'REJECTED'::character varying, 'ARCHIVED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: request_status_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.request_status_history (
    id bigint NOT NULL,
    previous_status character varying(30),
    new_status character varying(30) NOT NULL,
    notes_encrypted bytea,
    encryption_key_version smallint DEFAULT 1 NOT NULL,
    change_source character varying(20) DEFAULT 'WEB'::character varying NOT NULL,
    changed_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    changed_by_id uuid,
    request_id uuid NOT NULL,
    CONSTRAINT ck_rsh_change_source CHECK (((change_source)::text = ANY ((ARRAY['WEB'::character varying, 'CELERY'::character varying, 'SYSTEM'::character varying, 'COMMAND'::character varying, 'API'::character varying])::text[]))),
    CONSTRAINT ck_rsh_key_version CHECK ((encryption_key_version > 0))
);


--
-- Name: request_status_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.request_status_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.request_status_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: retention_rules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.retention_rules (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    entity_type character varying(50) NOT NULL,
    retention_days integer NOT NULL,
    retention_anchor character varying(30) NOT NULL,
    final_action character varying(20) NOT NULL,
    requires_approval boolean DEFAULT true NOT NULL,
    legal_basis text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_retention_action CHECK (((final_action)::text = ANY ((ARRAY['DELETE'::character varying, 'ANONYMIZE'::character varying, 'BLOCK'::character varying, 'ARCHIVE'::character varying])::text[]))),
    CONSTRAINT ck_retention_anchor CHECK (((retention_anchor)::text = ANY ((ARRAY['CREATED_AT'::character varying, 'RECEIVED_AT'::character varying, 'CLOSED_AT'::character varying, 'EXPIRES_AT'::character varying, 'REVOKED_AT'::character varying, 'LAST_ACTIVITY_AT'::character varying])::text[]))),
    CONSTRAINT ck_retention_days CHECK ((retention_days > 0))
);


--
-- Name: right_rules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.right_rules (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    response_days integer DEFAULT 15 NOT NULL,
    day_count_type character varying(20) DEFAULT 'BUSINESS'::character varying NOT NULL,
    extension_allowed boolean DEFAULT false NOT NULL,
    extension_days integer DEFAULT 0 NOT NULL,
    warning_days integer DEFAULT 2 NOT NULL,
    clarification_effect character varying(20) DEFAULT 'NO_CHANGE'::character varying NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    right_id uuid NOT NULL,
    CONSTRAINT ck_right_rules_clarification_effect CHECK (((clarification_effect)::text = ANY ((ARRAY['NO_CHANGE'::character varying, 'PAUSE'::character varying, 'RESTART'::character varying])::text[]))),
    CONSTRAINT ck_right_rules_day_count_type CHECK (((day_count_type)::text = ANY ((ARRAY['BUSINESS'::character varying, 'CALENDAR'::character varying])::text[]))),
    CONSTRAINT ck_right_rules_extension_consistency CHECK ((extension_allowed OR (extension_days = 0))),
    CONSTRAINT ck_right_rules_extension_days CHECK ((extension_days >= 0)),
    CONSTRAINT ck_right_rules_response_days CHECK ((response_days > 0)),
    CONSTRAINT ck_right_rules_warning_days CHECK ((warning_days >= 0))
);


--
-- Name: rights_catalog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rights_catalog (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(150) NOT NULL,
    description text,
    legal_reference character varying(250),
    is_active boolean DEFAULT true NOT NULL
);


--
-- Name: rights_request_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.rights_request_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: rights_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rights_requests (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    reference_number character varying(50) NOT NULL,
    request_details_encrypted bytea NOT NULL,
    subject_snapshot_encrypted bytea NOT NULL,
    encryption_key_version smallint DEFAULT 1 NOT NULL,
    snapshot_key_version smallint DEFAULT 1 NOT NULL,
    source_channel character varying(20) DEFAULT 'WEB'::character varying NOT NULL,
    status character varying(30) DEFAULT 'RECEIVED'::character varying NOT NULL,
    identity_status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    received_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    current_due_at timestamp with time zone,
    extension_applied boolean DEFAULT false NOT NULL,
    extension_reason_encrypted bytea,
    responded_at timestamp with time zone,
    closed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    assigned_to_id uuid,
    data_subject_id uuid NOT NULL,
    representative_id uuid,
    right_id uuid NOT NULL,
    CONSTRAINT ck_rr_closed_after_received CHECK (((closed_at IS NULL) OR (closed_at >= received_at))),
    CONSTRAINT ck_rr_encryption_key_version CHECK ((encryption_key_version > 0)),
    CONSTRAINT ck_rr_extension_reason CHECK (((NOT extension_applied) OR (extension_reason_encrypted IS NOT NULL))),
    CONSTRAINT ck_rr_identity_status CHECK (((identity_status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying, 'REQUIRES_REVIEW'::character varying])::text[]))),
    CONSTRAINT ck_rr_responded_after_received CHECK (((responded_at IS NULL) OR (responded_at >= received_at))),
    CONSTRAINT ck_rr_snapshot_key_version CHECK ((snapshot_key_version > 0)),
    CONSTRAINT ck_rr_source_channel CHECK (((source_channel)::text = ANY ((ARRAY['WEB'::character varying, 'EMAIL'::character varying, 'PHYSICAL'::character varying, 'PHONE'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT ck_rr_status CHECK (((status)::text = ANY ((ARRAY['RECEIVED'::character varying, 'UNDER_REVIEW'::character varying, 'AWAITING_INFORMATION'::character varying, 'EXTENDED'::character varying, 'PARTIALLY_APPROVED'::character varying, 'RESPONDED'::character varying, 'REJECTED'::character varying, 'ARCHIVED'::character varying, 'CANCELLED'::character varying, 'CLOSED'::character varying])::text[])))
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    code character varying(30) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_roles_code_valid CHECK (((code)::text = ANY ((ARRAY['ADMIN'::character varying, 'DPD'::character varying, 'RESPONSABLE'::character varying, 'OPERADOR'::character varying, 'AUDITOR'::character varying])::text[])))
);


--
-- Name: subject_representatives; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subject_representatives (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    representative_name_encrypted bytea NOT NULL,
    representative_document_type character varying(20) NOT NULL,
    representative_document_encrypted bytea CONSTRAINT subject_representatives_representative_document_encryp_not_null NOT NULL,
    representative_document_lookup_hash character(64) CONSTRAINT subject_representatives_representative_document_lookup_not_null NOT NULL,
    representative_email_encrypted bytea,
    encryption_key_version smallint DEFAULT 1 NOT NULL,
    lookup_key_version smallint DEFAULT 1 NOT NULL,
    verification_status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    verified_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    data_subject_id uuid NOT NULL,
    verified_by_id uuid,
    CONSTRAINT ck_representative_document_type CHECK (((representative_document_type)::text = ANY ((ARRAY['CEDULA'::character varying, 'RUC'::character varying, 'PASSPORT'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT ck_representative_encryption_key_version CHECK ((encryption_key_version > 0)),
    CONSTRAINT ck_representative_lookup_key_version CHECK ((lookup_key_version > 0)),
    CONSTRAINT ck_representative_verification_status CHECK (((verification_status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying])::text[]))),
    CONSTRAINT ck_representative_verified_timestamp CHECK (((NOT ((verification_status)::text = 'VERIFIED'::text)) OR (verified_at IS NOT NULL)))
);


--
-- Name: system_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.system_settings (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    singleton_key smallint DEFAULT 1 NOT NULL,
    legal_name character varying(180) NOT NULL,
    trade_name character varying(180),
    ruc character varying(13) NOT NULL,
    domain public.citext NOT NULL,
    address text,
    phone character varying(30),
    contact_email public.citext NOT NULL,
    controller_name character varying(180),
    controller_email public.citext,
    controller_phone character varying(30),
    dpd_name character varying(180),
    dpd_email public.citext,
    dpd_phone character varying(30),
    complaint_authority_name character varying(180) DEFAULT 'Superintendencia de Protección de Datos Personales'::character varying NOT NULL,
    complaint_channel_url text,
    complaint_instructions text,
    request_prefix character varying(10) NOT NULL,
    timezone character varying(50) DEFAULT 'America/Guayaquil'::character varying NOT NULL,
    logo_url text,
    favicon_url text,
    primary_color character varying(7),
    secondary_color character varying(7),
    accent_color character varying(7),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_system_settings_accent_color CHECK (((accent_color IS NULL) OR ((accent_color)::text ~ '^#[0-9A-Fa-f]{6}$'::text))),
    CONSTRAINT ck_system_settings_primary_color CHECK (((primary_color IS NULL) OR ((primary_color)::text ~ '^#[0-9A-Fa-f]{6}$'::text))),
    CONSTRAINT ck_system_settings_secondary_color CHECK (((secondary_color IS NULL) OR ((secondary_color)::text ~ '^#[0-9A-Fa-f]{6}$'::text))),
    CONSTRAINT ck_system_settings_singleton CHECK ((singleton_key = 1))
);


--
-- Name: temporary_uploads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.temporary_uploads (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    session_key_hash character(64) NOT NULL,
    upload_token_hash character(64) NOT NULL,
    lookup_key_version smallint DEFAULT 1 NOT NULL,
    attachment_type character varying(40) NOT NULL,
    original_filename_encrypted bytea NOT NULL,
    storage_backend character varying(20) DEFAULT 'LOCAL'::character varying NOT NULL,
    storage_key text NOT NULL,
    mime_type character varying(120) NOT NULL,
    size_bytes bigint NOT NULL,
    file_sha256 character(64) NOT NULL,
    is_encrypted boolean DEFAULT true NOT NULL,
    encryption_key_version smallint DEFAULT 1 NOT NULL,
    malware_scan_status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    status character varying(20) DEFAULT 'UPLOADED'::character varying NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    promoted_at timestamp with time zone,
    deleted_at timestamp with time zone,
    promoted_attachment_id uuid,
    promoted_request_id uuid,
    CONSTRAINT ck_tmp_expiration CHECK ((expires_at > created_at)),
    CONSTRAINT ck_tmp_key_version CHECK ((encryption_key_version > 0)),
    CONSTRAINT ck_tmp_lookup_version CHECK ((lookup_key_version > 0)),
    CONSTRAINT ck_tmp_promoted CHECK (((NOT ((status)::text = 'PROMOTED'::text)) OR ((promoted_request_id IS NOT NULL) AND (promoted_attachment_id IS NOT NULL) AND (promoted_at IS NOT NULL)))),
    CONSTRAINT ck_tmp_scan_status CHECK (((malware_scan_status)::text = ANY ((ARRAY['PENDING'::character varying, 'CLEAN'::character varying, 'INFECTED'::character varying, 'FAILED'::character varying, 'NOT_APPLICABLE'::character varying])::text[]))),
    CONSTRAINT ck_tmp_size CHECK ((size_bytes > 0)),
    CONSTRAINT ck_tmp_status CHECK (((status)::text = ANY ((ARRAY['UPLOADED'::character varying, 'PROMOTED'::character varying, 'QUARANTINED'::character varying, 'EXPIRED'::character varying, 'DELETED'::character varying])::text[]))),
    CONSTRAINT ck_tmp_storage CHECK (((storage_backend)::text = ANY ((ARRAY['LOCAL'::character varying, 'S3'::character varying, 'MINIO'::character varying])::text[]))),
    CONSTRAINT ck_tmp_type CHECK (((attachment_type)::text = ANY ((ARRAY['IDENTITY_DOCUMENT'::character varying, 'AUTHORITY_DOCUMENT'::character varying, 'SUPPORTING_DOCUMENT'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_roles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    is_primary boolean DEFAULT false NOT NULL,
    assigned_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    revoked_at timestamp with time zone,
    assigned_by uuid,
    role_id uuid NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT ck_user_roles_revoked_after_assigned CHECK (((revoked_at IS NULL) OR (revoked_at >= assigned_at)))
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email public.citext NOT NULL,
    full_name character varying(180) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    is_staff boolean DEFAULT false NOT NULL,
    is_superuser boolean DEFAULT false NOT NULL,
    failed_login_attempts integer DEFAULT 0 NOT NULL,
    locked_until timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_users_failed_login_attempts_nonnegative CHECK ((failed_login_attempts >= 0))
);


--
-- Name: audit_logs audit_logs_entry_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_entry_hash_key UNIQUE (entry_hash);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: business_holidays business_holidays_holiday_date_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_holidays
    ADD CONSTRAINT business_holidays_holiday_date_key UNIQUE (holiday_date);


--
-- Name: business_holidays business_holidays_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_holidays
    ADD CONSTRAINT business_holidays_pkey PRIMARY KEY (id);


--
-- Name: case_outcome_reasons case_outcome_reasons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.case_outcome_reasons
    ADD CONSTRAINT case_outcome_reasons_pkey PRIMARY KEY (id);


--
-- Name: data_disposal_events data_disposal_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_disposal_events
    ADD CONSTRAINT data_disposal_events_pkey PRIMARY KEY (id);


--
-- Name: data_subjects data_subjects_document_number_lookup_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_subjects
    ADD CONSTRAINT data_subjects_document_number_lookup_hash_key UNIQUE (document_number_lookup_hash);


--
-- Name: data_subjects data_subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_subjects
    ADD CONSTRAINT data_subjects_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: identity_verifications identity_verifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.identity_verifications
    ADD CONSTRAINT identity_verifications_pkey PRIMARY KEY (id);


--
-- Name: legal_documents legal_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.legal_documents
    ADD CONSTRAINT legal_documents_pkey PRIMARY KEY (id);


--
-- Name: mfa_devices mfa_devices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mfa_devices
    ADD CONSTRAINT mfa_devices_pkey PRIMARY KEY (id);


--
-- Name: notice_deliveries notice_deliveries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notice_deliveries
    ADD CONSTRAINT notice_deliveries_pkey PRIMARY KEY (id);


--
-- Name: portability_exports portability_exports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.portability_exports
    ADD CONSTRAINT portability_exports_pkey PRIMARY KEY (id);


--
-- Name: portability_exports portability_exports_storage_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.portability_exports
    ADD CONSTRAINT portability_exports_storage_key_key UNIQUE (storage_key);


--
-- Name: request_access_tokens request_access_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_access_tokens
    ADD CONSTRAINT request_access_tokens_pkey PRIMARY KEY (id);


--
-- Name: request_access_tokens request_access_tokens_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_access_tokens
    ADD CONSTRAINT request_access_tokens_token_hash_key UNIQUE (token_hash);


--
-- Name: request_attachments request_attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_attachments
    ADD CONSTRAINT request_attachments_pkey PRIMARY KEY (id);


--
-- Name: request_attachments request_attachments_storage_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_attachments
    ADD CONSTRAINT request_attachments_storage_key_key UNIQUE (storage_key);


--
-- Name: request_clarifications request_clarifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_clarifications
    ADD CONSTRAINT request_clarifications_pkey PRIMARY KEY (id);


--
-- Name: request_communications request_communications_idempotency_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_communications
    ADD CONSTRAINT request_communications_idempotency_key_key UNIQUE (idempotency_key);


--
-- Name: request_communications request_communications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_communications
    ADD CONSTRAINT request_communications_pkey PRIMARY KEY (id);


--
-- Name: request_deadlines request_deadlines_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_deadlines
    ADD CONSTRAINT request_deadlines_pkey PRIMARY KEY (id);


--
-- Name: request_resolutions request_resolutions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_resolutions
    ADD CONSTRAINT request_resolutions_pkey PRIMARY KEY (id);


--
-- Name: request_resolutions request_resolutions_request_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_resolutions
    ADD CONSTRAINT request_resolutions_request_id_key UNIQUE (request_id);


--
-- Name: request_status_history request_status_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_status_history
    ADD CONSTRAINT request_status_history_pkey PRIMARY KEY (id);


--
-- Name: retention_rules retention_rules_entity_type_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.retention_rules
    ADD CONSTRAINT retention_rules_entity_type_key UNIQUE (entity_type);


--
-- Name: retention_rules retention_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.retention_rules
    ADD CONSTRAINT retention_rules_pkey PRIMARY KEY (id);


--
-- Name: right_rules right_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.right_rules
    ADD CONSTRAINT right_rules_pkey PRIMARY KEY (id);


--
-- Name: right_rules right_rules_right_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.right_rules
    ADD CONSTRAINT right_rules_right_id_key UNIQUE (right_id);


--
-- Name: rights_catalog rights_catalog_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rights_catalog
    ADD CONSTRAINT rights_catalog_code_key UNIQUE (code);


--
-- Name: rights_catalog rights_catalog_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rights_catalog
    ADD CONSTRAINT rights_catalog_pkey PRIMARY KEY (id);


--
-- Name: rights_requests rights_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rights_requests
    ADD CONSTRAINT rights_requests_pkey PRIMARY KEY (id);


--
-- Name: rights_requests rights_requests_reference_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rights_requests
    ADD CONSTRAINT rights_requests_reference_number_key UNIQUE (reference_number);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: subject_representatives subject_representatives_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subject_representatives
    ADD CONSTRAINT subject_representatives_pkey PRIMARY KEY (id);


--
-- Name: system_settings system_settings_domain_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.system_settings
    ADD CONSTRAINT system_settings_domain_key UNIQUE (domain);


--
-- Name: system_settings system_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.system_settings
    ADD CONSTRAINT system_settings_pkey PRIMARY KEY (id);


--
-- Name: system_settings system_settings_singleton_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.system_settings
    ADD CONSTRAINT system_settings_singleton_key_key UNIQUE (singleton_key);


--
-- Name: temporary_uploads temporary_uploads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.temporary_uploads
    ADD CONSTRAINT temporary_uploads_pkey PRIMARY KEY (id);


--
-- Name: temporary_uploads temporary_uploads_storage_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.temporary_uploads
    ADD CONSTRAINT temporary_uploads_storage_key_key UNIQUE (storage_key);


--
-- Name: temporary_uploads temporary_uploads_upload_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.temporary_uploads
    ADD CONSTRAINT temporary_uploads_upload_token_hash_key UNIQUE (upload_token_hash);


--
-- Name: audit_logs uq_audit_chain_position; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT uq_audit_chain_position UNIQUE (chain_scope, chain_position);


--
-- Name: case_outcome_reasons uq_cor_type_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.case_outcome_reasons
    ADD CONSTRAINT uq_cor_type_code UNIQUE (reason_type, code);


--
-- Name: legal_documents uq_legal_document_slug_version; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.legal_documents
    ADD CONSTRAINT uq_legal_document_slug_version UNIQUE (slug, version);


--
-- Name: legal_documents uq_legal_document_type_version; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.legal_documents
    ADD CONSTRAINT uq_legal_document_type_version UNIQUE (document_type, version);


--
-- Name: request_deadlines uq_rd_request_type_seq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_deadlines
    ADD CONSTRAINT uq_rd_request_type_seq UNIQUE (request_id, deadline_type, sequence_number);


--
-- Name: subject_representatives uq_representative_id_subject; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subject_representatives
    ADD CONSTRAINT uq_representative_id_subject UNIQUE (id, data_subject_id);


--
-- Name: subject_representatives uq_representative_subject_document; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subject_representatives
    ADD CONSTRAINT uq_representative_subject_document UNIQUE (data_subject_id, representative_document_lookup_hash);


--
-- Name: roles uq_roles_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT uq_roles_code UNIQUE (code);


--
-- Name: system_settings uq_system_settings_ruc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.system_settings
    ADD CONSTRAINT uq_system_settings_ruc UNIQUE (ruc);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: idx_att_rep; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_att_rep ON public.request_attachments USING btree (representative_id) WHERE (representative_id IS NOT NULL);


--
-- Name: idx_att_request; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_att_request ON public.request_attachments USING btree (request_id, uploaded_at DESC);


--
-- Name: idx_att_visible; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_att_visible ON public.request_attachments USING btree (request_id, visibility) WHERE (deleted_at IS NULL);


--
-- Name: idx_audit_actor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_actor ON public.audit_logs USING btree (actor_user_id, created_at DESC) WHERE (actor_user_id IS NOT NULL);


--
-- Name: idx_audit_correlation; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_correlation ON public.audit_logs USING btree (correlation_id);


--
-- Name: idx_audit_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_created_at ON public.audit_logs USING btree (created_at DESC);


--
-- Name: idx_audit_entity; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_entity ON public.audit_logs USING btree (entity_type, entity_pk, created_at DESC);


--
-- Name: idx_clar_request; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_clar_request ON public.request_clarifications USING btree (request_id, requested_at DESC);


--
-- Name: idx_comm_pending; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comm_pending ON public.request_communications USING btree (next_retry_at, queued_at) WHERE ((delivery_status)::text = ANY ((ARRAY['PENDING'::character varying, 'FAILED'::character varying])::text[]));


--
-- Name: idx_comm_request; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comm_request ON public.request_communications USING btree (request_id, created_at DESC);


--
-- Name: idx_comm_visible; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comm_visible ON public.request_communications USING btree (request_id, created_at DESC) WHERE visible_to_subject;


--
-- Name: idx_cor_type_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cor_type_active ON public.case_outcome_reasons USING btree (reason_type, code) WHERE is_active;


--
-- Name: idx_disposal_pending; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_disposal_pending ON public.data_disposal_events USING btree (status, detected_at) WHERE ((status)::text = ANY ((ARRAY['DETECTED'::character varying, 'PENDING_APPROVAL'::character varying, 'APPROVED'::character varying])::text[]));


--
-- Name: idx_disposal_rule; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_disposal_rule ON public.data_disposal_events USING btree (retention_rule_id) WHERE (retention_rule_id IS NOT NULL);


--
-- Name: idx_ds_email_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ds_email_lookup ON public.data_subjects USING btree (email_lookup_hash);


--
-- Name: idx_idv_actor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_idv_actor ON public.identity_verifications USING btree (verified_by_id, created_at DESC) WHERE (verified_by_id IS NOT NULL);


--
-- Name: idx_idv_request; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_idv_request ON public.identity_verifications USING btree (request_id, created_at DESC);


--
-- Name: idx_legal_documents_creator; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_legal_documents_creator ON public.legal_documents USING btree (created_by_id) WHERE (created_by_id IS NOT NULL);


--
-- Name: idx_mfa_devices_user_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mfa_devices_user_active ON public.mfa_devices USING btree (user_id) WHERE (is_active AND (revoked_at IS NULL));


--
-- Name: idx_notice_doc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notice_doc ON public.notice_deliveries USING btree (legal_document_id);


--
-- Name: idx_notice_request; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notice_request ON public.notice_deliveries USING btree (request_id, delivered_at DESC);


--
-- Name: idx_portability_expiration; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_portability_expiration ON public.portability_exports USING btree (expires_at) WHERE ((revoked_at IS NULL) AND (expires_at IS NOT NULL));


--
-- Name: idx_portability_request; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_portability_request ON public.portability_exports USING btree (request_id, generated_at DESC);


--
-- Name: idx_rat_expiration; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rat_expiration ON public.request_access_tokens USING btree (expires_at) WHERE (revoked_at IS NULL);


--
-- Name: idx_rat_request; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rat_request ON public.request_access_tokens USING btree (request_id, purpose);


--
-- Name: idx_rd_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rd_active ON public.request_deadlines USING btree (due_at) WHERE ((status)::text = 'ACTIVE'::text);


--
-- Name: idx_rd_request; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rd_request ON public.request_deadlines USING btree (request_id, sequence_number);


--
-- Name: idx_rep_doc_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rep_doc_lookup ON public.subject_representatives USING btree (representative_document_lookup_hash);


--
-- Name: idx_representatives_subject; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_representatives_subject ON public.subject_representatives USING btree (data_subject_id);


--
-- Name: idx_resolution_actor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resolution_actor ON public.request_resolutions USING btree (resolved_by_id, resolved_at DESC);


--
-- Name: idx_rr_assigned; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rr_assigned ON public.rights_requests USING btree (assigned_to_id, status);


--
-- Name: idx_rr_due; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rr_due ON public.rights_requests USING btree (current_due_at) WHERE (NOT ((status)::text = ANY ((ARRAY['RESPONDED'::character varying, 'REJECTED'::character varying, 'ARCHIVED'::character varying, 'CANCELLED'::character varying, 'CLOSED'::character varying])::text[])));


--
-- Name: idx_rr_received; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rr_received ON public.rights_requests USING btree (received_at DESC);


--
-- Name: idx_rr_right; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rr_right ON public.rights_requests USING btree (right_id);


--
-- Name: idx_rr_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rr_status ON public.rights_requests USING btree (status);


--
-- Name: idx_rr_subject; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rr_subject ON public.rights_requests USING btree (data_subject_id);


--
-- Name: idx_rsh_actor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rsh_actor ON public.request_status_history USING btree (changed_by_id, changed_at DESC) WHERE (changed_by_id IS NOT NULL);


--
-- Name: idx_rsh_request; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rsh_request ON public.request_status_history USING btree (request_id, changed_at DESC);


--
-- Name: idx_tmp_expiry; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tmp_expiry ON public.temporary_uploads USING btree (expires_at) WHERE ((status)::text = 'UPLOADED'::text);


--
-- Name: idx_tmp_session; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tmp_session ON public.temporary_uploads USING btree (session_key_hash, status);


--
-- Name: idx_user_roles_role_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_roles_role_active ON public.user_roles USING btree (role_id, user_id) WHERE (revoked_at IS NULL);


--
-- Name: idx_user_roles_user_history; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_roles_user_history ON public.user_roles USING btree (user_id, assigned_at DESC);


--
-- Name: portability_exports_storage_key_c40c6e32_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX portability_exports_storage_key_c40c6e32_like ON public.portability_exports USING btree (storage_key text_pattern_ops);


--
-- Name: request_attachments_storage_key_c9ca5a6f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX request_attachments_storage_key_c9ca5a6f_like ON public.request_attachments USING btree (storage_key text_pattern_ops);


--
-- Name: retention_rules_entity_type_71215817_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX retention_rules_entity_type_71215817_like ON public.retention_rules USING btree (entity_type varchar_pattern_ops);


--
-- Name: rights_catalog_code_ce3a09ba_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rights_catalog_code_ce3a09ba_like ON public.rights_catalog USING btree (code varchar_pattern_ops);


--
-- Name: rights_requests_reference_number_5633b25c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rights_requests_reference_number_5633b25c_like ON public.rights_requests USING btree (reference_number varchar_pattern_ops);


--
-- Name: temporary_uploads_storage_key_cb198900_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX temporary_uploads_storage_key_cb198900_like ON public.temporary_uploads USING btree (storage_key text_pattern_ops);


--
-- Name: uq_disposal_open_event; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_disposal_open_event ON public.data_disposal_events USING btree (entity_type, entity_pk, action) WHERE ((status)::text = ANY ((ARRAY['DETECTED'::character varying, 'PENDING_APPROVAL'::character varying, 'APPROVED'::character varying])::text[]));


--
-- Name: uq_legal_document_active_type; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_legal_document_active_type ON public.legal_documents USING btree (document_type) WHERE ((effective_to IS NULL) AND is_published);


--
-- Name: uq_user_active_role; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_user_active_role ON public.user_roles USING btree (user_id, role_id) WHERE (revoked_at IS NULL);


--
-- Name: uq_user_primary_role; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_user_primary_role ON public.user_roles USING btree (user_id) WHERE (is_primary AND (revoked_at IS NULL));


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: request_access_tokens fk_access_tokens_request; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_access_tokens
    ADD CONSTRAINT fk_access_tokens_request FOREIGN KEY (request_id) REFERENCES public.rights_requests(id) ON DELETE CASCADE;


--
-- Name: request_attachments fk_attachments_representative; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_attachments
    ADD CONSTRAINT fk_attachments_representative FOREIGN KEY (representative_id) REFERENCES public.subject_representatives(id) ON DELETE SET NULL;


--
-- Name: request_attachments fk_attachments_request; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_attachments
    ADD CONSTRAINT fk_attachments_request FOREIGN KEY (request_id) REFERENCES public.rights_requests(id) ON DELETE CASCADE;


--
-- Name: request_attachments fk_attachments_uploaded_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_attachments
    ADD CONSTRAINT fk_attachments_uploaded_by FOREIGN KEY (uploaded_by_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: audit_logs fk_audit_actor_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT fk_audit_actor_user FOREIGN KEY (actor_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: request_clarifications fk_clarifications_created_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_clarifications
    ADD CONSTRAINT fk_clarifications_created_by FOREIGN KEY (created_by_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: request_clarifications fk_clarifications_request; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_clarifications
    ADD CONSTRAINT fk_clarifications_request FOREIGN KEY (request_id) REFERENCES public.rights_requests(id) ON DELETE CASCADE;


--
-- Name: request_communications fk_communications_request; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_communications
    ADD CONSTRAINT fk_communications_request FOREIGN KEY (request_id) REFERENCES public.rights_requests(id) ON DELETE CASCADE;


--
-- Name: request_communications fk_communications_sent_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_communications
    ADD CONSTRAINT fk_communications_sent_by FOREIGN KEY (sent_by_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: request_deadlines fk_deadlines_request; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_deadlines
    ADD CONSTRAINT fk_deadlines_request FOREIGN KEY (request_id) REFERENCES public.rights_requests(id) ON DELETE CASCADE;


--
-- Name: data_disposal_events fk_disposal_approved_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_disposal_events
    ADD CONSTRAINT fk_disposal_approved_by FOREIGN KEY (approved_by_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: data_disposal_events fk_disposal_executed_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_disposal_events
    ADD CONSTRAINT fk_disposal_executed_by FOREIGN KEY (executed_by_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: data_disposal_events fk_disposal_retention_rule; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_disposal_events
    ADD CONSTRAINT fk_disposal_retention_rule FOREIGN KEY (retention_rule_id) REFERENCES public.retention_rules(id) ON DELETE SET NULL;


--
-- Name: identity_verifications fk_idv_request; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.identity_verifications
    ADD CONSTRAINT fk_idv_request FOREIGN KEY (request_id) REFERENCES public.rights_requests(id) ON DELETE CASCADE;


--
-- Name: identity_verifications fk_idv_verified_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.identity_verifications
    ADD CONSTRAINT fk_idv_verified_by FOREIGN KEY (verified_by_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: legal_documents fk_legal_documents_created_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.legal_documents
    ADD CONSTRAINT fk_legal_documents_created_by FOREIGN KEY (created_by_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: mfa_devices fk_mfa_devices_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mfa_devices
    ADD CONSTRAINT fk_mfa_devices_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: notice_deliveries fk_notice_legal_document; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notice_deliveries
    ADD CONSTRAINT fk_notice_legal_document FOREIGN KEY (legal_document_id) REFERENCES public.legal_documents(id) ON DELETE RESTRICT;


--
-- Name: notice_deliveries fk_notice_request; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notice_deliveries
    ADD CONSTRAINT fk_notice_request FOREIGN KEY (request_id) REFERENCES public.rights_requests(id) ON DELETE CASCADE;


--
-- Name: portability_exports fk_portability_generated_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.portability_exports
    ADD CONSTRAINT fk_portability_generated_by FOREIGN KEY (generated_by_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: portability_exports fk_portability_request; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.portability_exports
    ADD CONSTRAINT fk_portability_request FOREIGN KEY (request_id) REFERENCES public.rights_requests(id) ON DELETE CASCADE;


--
-- Name: subject_representatives fk_representatives_subject; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subject_representatives
    ADD CONSTRAINT fk_representatives_subject FOREIGN KEY (data_subject_id) REFERENCES public.data_subjects(id) ON DELETE CASCADE;


--
-- Name: subject_representatives fk_representatives_verified_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subject_representatives
    ADD CONSTRAINT fk_representatives_verified_by FOREIGN KEY (verified_by_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: rights_requests fk_request_representative_same_subject; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rights_requests
    ADD CONSTRAINT fk_request_representative_same_subject FOREIGN KEY (representative_id, data_subject_id) REFERENCES public.subject_representatives(id, data_subject_id) ON DELETE RESTRICT;


--
-- Name: request_resolutions fk_resolutions_outcome_reason; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_resolutions
    ADD CONSTRAINT fk_resolutions_outcome_reason FOREIGN KEY (outcome_reason_id) REFERENCES public.case_outcome_reasons(id) ON DELETE RESTRICT;


--
-- Name: request_resolutions fk_resolutions_request; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_resolutions
    ADD CONSTRAINT fk_resolutions_request FOREIGN KEY (request_id) REFERENCES public.rights_requests(id) ON DELETE CASCADE;


--
-- Name: request_resolutions fk_resolutions_resolved_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_resolutions
    ADD CONSTRAINT fk_resolutions_resolved_by FOREIGN KEY (resolved_by_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: right_rules fk_right_rules_right; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.right_rules
    ADD CONSTRAINT fk_right_rules_right FOREIGN KEY (right_id) REFERENCES public.rights_catalog(id) ON DELETE RESTRICT;


--
-- Name: rights_requests fk_rights_requests_assigned_to; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rights_requests
    ADD CONSTRAINT fk_rights_requests_assigned_to FOREIGN KEY (assigned_to_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: rights_requests fk_rights_requests_right; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rights_requests
    ADD CONSTRAINT fk_rights_requests_right FOREIGN KEY (right_id) REFERENCES public.rights_catalog(id) ON DELETE RESTRICT;


--
-- Name: rights_requests fk_rights_requests_subject; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rights_requests
    ADD CONSTRAINT fk_rights_requests_subject FOREIGN KEY (data_subject_id) REFERENCES public.data_subjects(id) ON DELETE RESTRICT;


--
-- Name: request_status_history fk_status_history_changed_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_status_history
    ADD CONSTRAINT fk_status_history_changed_by FOREIGN KEY (changed_by_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: request_status_history fk_status_history_request; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_status_history
    ADD CONSTRAINT fk_status_history_request FOREIGN KEY (request_id) REFERENCES public.rights_requests(id) ON DELETE CASCADE;


--
-- Name: temporary_uploads fk_tmp_promoted_attachment; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.temporary_uploads
    ADD CONSTRAINT fk_tmp_promoted_attachment FOREIGN KEY (promoted_attachment_id) REFERENCES public.request_attachments(id) ON DELETE SET NULL;


--
-- Name: temporary_uploads fk_tmp_promoted_request; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.temporary_uploads
    ADD CONSTRAINT fk_tmp_promoted_request FOREIGN KEY (promoted_request_id) REFERENCES public.rights_requests(id) ON DELETE SET NULL;


--
-- Name: user_roles fk_user_roles_assigned_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fk_user_roles_assigned_by FOREIGN KEY (assigned_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: user_roles fk_user_roles_role; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE RESTRICT;


--
-- Name: user_roles fk_user_roles_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 1HsGSfMaVpoxD8lEj2dSxNiQkgnL2gi1YTwjHf2fhcZDRgPt6nvpQXzlq3jQB1w

