# Generated by Django 5.2.16 on 2026-08-17 15:11

import apps.core.fields
import django.contrib.postgres.functions
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RightCatalog',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('legal_reference', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
            ],
            options={
                'db_table': 'rights_catalog',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('PRIVACY_POLICY', 'Política de Privacidad'), ('EMPLOYEE_NOTICE', 'Aviso Empleados'), ('CANDIDATE_NOTICE', 'Aviso Candidatos'), ('CUSTOMER_VENDOR_NOTICE', 'Aviso Clientes/Vendedores'), ('SUPPLIER_NOTICE', 'Aviso Proveedores'), ('VIDEO_SURVEILLANCE_NOTICE', 'Aviso Videovigilancia'), ('RIGHTS_NOTICE', 'Derechos y Contacto'), ('COOKIES_POLICY', 'Política de Cookies'), ('OTHER', 'Otro')], max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=180)),
                ('version', models.CharField(max_length=30)),
                ('content_html', models.TextField()),
                ('content_sha256', apps.core.fields.FixedCharField(max_length=64)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(db_default=False, default=False)),
                ('created_at', models.DateTimeField(db_default=django.contrib.postgres.functions.TransactionNow(), editable=False)),
                ('created_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_documents_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'legal_documents',
                'ordering': ['document_type', '-effective_from'],
                'indexes': [models.Index(condition=models.Q(('created_by__isnull', False)), fields=['created_by'], name='idx_legal_documents_creator')],
                'constraints': [models.CheckConstraint(condition=models.Q(('document_type__in', ['PRIVACY_POLICY', 'EMPLOYEE_NOTICE', 'CANDIDATE_NOTICE', 'CUSTOMER_VENDOR_NOTICE', 'SUPPLIER_NOTICE', 'VIDEO_SURVEILLANCE_NOTICE', 'RIGHTS_NOTICE', 'COOKIES_POLICY', 'OTHER'])), name='ck_legal_document_type_valid'), models.UniqueConstraint(fields=('document_type', 'version'), name='uq_legal_document_type_version'), models.UniqueConstraint(fields=('slug', 'version'), name='uq_legal_document_slug_version'), models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True), ('is_published', True)), fields=('document_type',), name='uq_legal_document_active_type'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='ck_legal_document_effective_dates')],
            },
        ),
        migrations.CreateModel(
            name='RightRule',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_days', models.IntegerField(db_default=15, default=15)),
                ('day_count_type', models.CharField(choices=[('BUSINESS', 'Días hábiles'), ('CALENDAR', 'Días calendario')], db_default='BUSINESS', default='BUSINESS', max_length=20)),
                ('extension_allowed', models.BooleanField(db_default=False, default=False)),
                ('extension_days', models.IntegerField(db_default=0, default=0)),
                ('warning_days', models.IntegerField(db_default=2, default=2)),
                ('clarification_effect', models.CharField(choices=[('NO_CHANGE', 'Sin cambio'), ('PAUSE', 'Pausa'), ('RESTART', 'Reinicio')], db_default='NO_CHANGE', default='NO_CHANGE', max_length=20)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('right', models.OneToOneField(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='rule', to='legal_content.rightcatalog')),
            ],
            options={
                'db_table': 'right_rules',
                'constraints': [models.CheckConstraint(condition=models.Q(('response_days__gt', 0)), name='ck_right_rules_response_days'), models.CheckConstraint(condition=models.Q(('day_count_type__in', ['BUSINESS', 'CALENDAR'])), name='ck_right_rules_day_count_type'), models.CheckConstraint(condition=models.Q(('extension_days__gte', 0)), name='ck_right_rules_extension_days'), models.CheckConstraint(condition=models.Q(('warning_days__gte', 0)), name='ck_right_rules_warning_days'), models.CheckConstraint(condition=models.Q(('clarification_effect__in', ['NO_CHANGE', 'PAUSE', 'RESTART'])), name='ck_right_rules_clarification_effect'), models.CheckConstraint(condition=models.Q(('extension_allowed', True), ('extension_days', 0), _connector='OR'), name='ck_right_rules_extension_consistency')],
            },
        ),
    ]
